apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soperator-dcgm-exporter.name" . }}-service-monitor
  labels:
    app: nvidia-dcgm-exporter
  {{- include "soperator-dcgm-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.scrapeInterval }}
    path: /metrics
    port: gpu-metrics
    metricRelabelings:
    {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 4 }}
    relabelings:
    {{- toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
  jobLabel: app
  attachMetadata:
    node: true
  namespaceSelector:
    matchNames:
    - soperator
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
