package nodeconfigurator

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"k8s.io/utils/ptr"

	slurmv1alpha1 "nebius.ai/slurm-operator/api/v1alpha1"
	"nebius.ai/slurm-operator/internal/resourcepatch"
)

func patchTestScheme(t *testing.T) *runtime.Scheme {
	t.Helper()
	scheme := runtime.NewScheme()
	require.NoError(t, clientgoscheme.AddToScheme(scheme))
	require.NoError(t, slurmv1alpha1.AddToScheme(scheme))
	return scheme
}

func jsonValue(t *testing.T, v any) *apiextensionsv1.JSON {
	t.Helper()
	raw, err := json.Marshal(v)
	require.NoError(t, err)
	return &apiextensionsv1.JSON{Raw: raw}
}

func newNodeConfigurator() *slurmv1alpha1.NodeConfigurator {
	return &slurmv1alpha1.NodeConfigurator{
		ObjectMeta: metav1.ObjectMeta{Name: "node-configurator"},
		Spec: slurmv1alpha1.NodeConfiguratorSpec{
			Rebooter: slurmv1alpha1.Rebooter{Enabled: true},
		},
	}
}

// TestPatchNodeConfiguratorDaemonSet applies a ResourcePatchPolicy to the real
// DaemonSet generated by RenderDaemonSet.
func TestPatchNodeConfiguratorDaemonSet_AddAnnotationAndResources(t *testing.T) {
	scheme := patchTestScheme(t)
	ds := RenderDaemonSet(newNodeConfigurator(), "test-namespace")
	require.NotNil(t, ds)
	require.NotEmpty(t, ds.Spec.Template.Spec.Containers)

	policy := slurmv1alpha1.ResourcePatchPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "nc-patch", Namespace: "test-namespace"},
		Spec: slurmv1alpha1.ResourcePatchPolicySpec{
			TargetRef: slurmv1alpha1.PolicyTargetReference{
				Group: "slurm.nebius.ai", Kind: "NodeConfigurator", Name: "node-configurator",
			},
			Type: slurmv1alpha1.JSONPatchType,
			Patches: []slurmv1alpha1.ResourcePatch{
				{
					ResourceRef: slurmv1alpha1.ResourceSelector{
						Kind: "DaemonSet", Name: ptr.To(ds.Name),
					},
					JSONPatch: []slurmv1alpha1.JSONPatchOperation{
						{
							Op:    "add",
							Path:  "/spec/template/metadata/annotations",
							Value: jsonValue(t, map[string]string{"ad.datadoghq.com/inject": "true"}),
						},
						{
							Op:   "add",
							Path: "/spec/template/spec/containers/0/resources",
							Value: jsonValue(t, corev1.ResourceRequirements{
								Limits: corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("256Mi")},
							}),
						},
					},
				},
			},
		},
	}

	results, err := resourcepatch.Apply(scheme, ds, []slurmv1alpha1.ResourcePatchPolicy{policy})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)

	assert.Equal(t, "true", ds.Spec.Template.Annotations["ad.datadoghq.com/inject"])
	mem := ds.Spec.Template.Spec.Containers[0].Resources.Limits[corev1.ResourceMemory]
	assert.Equal(t, "256Mi", mem.String())

	// The operator-managed update strategy must remain intact.
	require.NotNil(t, ds.Spec.UpdateStrategy.RollingUpdate)
}

func TestPatchNodeConfiguratorDaemonSet_AddToleration(t *testing.T) {
	scheme := patchTestScheme(t)
	ds := RenderDaemonSet(newNodeConfigurator(), "test-namespace")
	before := len(ds.Spec.Template.Spec.Tolerations)

	tol := corev1.Toleration{Key: "dedicated", Operator: corev1.TolerationOpExists, Effect: corev1.TaintEffectNoSchedule}
	policy := slurmv1alpha1.ResourcePatchPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "nc-tol", Namespace: "test-namespace"},
		Spec: slurmv1alpha1.ResourcePatchPolicySpec{
			TargetRef: slurmv1alpha1.PolicyTargetReference{
				Group: "slurm.nebius.ai", Kind: "NodeConfigurator", Name: "node-configurator",
			},
			Type: slurmv1alpha1.JSONPatchType,
			Patches: []slurmv1alpha1.ResourcePatch{{
				ResourceRef: slurmv1alpha1.ResourceSelector{Kind: "DaemonSet", Name: ptr.To(ds.Name)},
				JSONPatch: []slurmv1alpha1.JSONPatchOperation{
					{Op: "add", Path: "/spec/template/spec/tolerations", Value: jsonValue(t, []corev1.Toleration{})},
					{Op: "add", Path: "/spec/template/spec/tolerations/-", Value: jsonValue(t, tol)},
				},
			}},
		},
	}

	results, err := resourcepatch.Apply(scheme, ds, []slurmv1alpha1.ResourcePatchPolicy{policy})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)
	require.Len(t, ds.Spec.Template.Spec.Tolerations, before+1)
	assert.Equal(t, "dedicated", ds.Spec.Template.Spec.Tolerations[before].Key)
}

func TestPatchNodeConfiguratorDaemonSet_RejectsSelectorChange(t *testing.T) {
	scheme := patchTestScheme(t)
	ds := RenderDaemonSet(newNodeConfigurator(), "test-namespace")
	require.NotNil(t, ds.Spec.Selector)
	originalSelector := ds.Spec.Selector.DeepCopy()

	policy := slurmv1alpha1.ResourcePatchPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "nc-bad", Namespace: "test-namespace"},
		Spec: slurmv1alpha1.ResourcePatchPolicySpec{
			TargetRef: slurmv1alpha1.PolicyTargetReference{
				Group: "slurm.nebius.ai", Kind: "NodeConfigurator", Name: "node-configurator",
			},
			Type: slurmv1alpha1.JSONPatchType,
			Patches: []slurmv1alpha1.ResourcePatch{{
				ResourceRef: slurmv1alpha1.ResourceSelector{Kind: "DaemonSet", Name: ptr.To(ds.Name)},
				JSONPatch: []slurmv1alpha1.JSONPatchOperation{
					{Op: "add", Path: "/spec/selector/matchLabels/hijack", Value: jsonValue(t, "yes")},
				},
			}},
		},
	}

	results, err := resourcepatch.Apply(scheme, ds, []slurmv1alpha1.ResourcePatchPolicy{policy})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.False(t, results[0].Applied, "selector change must be rejected")
	assert.Equal(t, originalSelector, ds.Spec.Selector, "selector must remain unchanged")
}
