package common

import (
	"nebius.ai/slurm-operator/internal/consts"
	renderutils "nebius.ai/slurm-operator/internal/render/utils"
)

const (
	slurmConfigDir = "/etc/slurm"

	managedSlurmConfigWarning = `# Managed by Soperator.
# Do not edit this file.
# Changes are overwritten.`

	slurmConfigEntrypointWarning = `# Managed by Soperator.
# Do not edit this file.
# Changes are overwritten.
# Generated settings are in slurm.gen.conf.
# Overrides are in override_slurm.conf.`

	overrideSlurmConfigWarning = `# Managed by Soperator.
# Do not edit this file.
# Changes are overwritten.
# Overrides are generated by Soperator.`
)

func RenderSlurmConfigEntrypoint() renderutils.ConfigFile {
	// Keep override_slurm.conf last so user overrides take precedence over
	// generated files and any future rootfs-provided config snippets.
	return renderutils.NewAsIsConfig(
		slurmConfigEntrypointWarning + "\n\n" +
			"include " + slurmConfigPath(consts.ConfigMapKeySlurmGenConfig) + "\n" +
			"include " + slurmConfigPath(consts.ConfigMapKeyCustomSlurmConfig),
	)
}

func WithManagedSlurmConfigWarning(config renderutils.ConfigFile) renderutils.ConfigFile {
	return renderutils.NewAsIsConfig(managedSlurmConfigWarning + "\n\n" + config.Render())
}

func WithOverrideSlurmConfigWarning(config renderutils.ConfigFile) renderutils.ConfigFile {
	return renderutils.NewAsIsConfig(overrideSlurmConfigWarning + "\n\n" + config.Render())
}

func ManagedSlurmConfigWarning() string {
	return managedSlurmConfigWarning
}

func SlurmConfigEntrypointWarning() string {
	return slurmConfigEntrypointWarning
}

func slurmConfigPath(fileName string) string {
	return slurmConfigDir + "/" + fileName
}
