/*
Copyright 2024 Nebius B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package resourcepatch_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/client"

	slurmv1alpha1 "nebius.ai/slurm-operator/api/v1alpha1"
	"nebius.ai/slurm-operator/internal/resourcepatch"
)

func testScheme(t *testing.T) *runtime.Scheme {
	t.Helper()
	scheme := runtime.NewScheme()
	require.NoError(t, clientgoscheme.AddToScheme(scheme))
	require.NoError(t, slurmv1alpha1.AddToScheme(scheme))
	return scheme
}

// jsonValue marshals v into an *apiextensionsv1.JSON for use as a JSON Patch
// operation value.
func jsonValue(t *testing.T, v any) *apiextensionsv1.JSON {
	t.Helper()
	raw, err := json.Marshal(v)
	require.NoError(t, err)
	return &apiextensionsv1.JSON{Raw: raw}
}

func mustQuantity(s string) resource.Quantity {
	return resource.MustParse(s)
}

// policy builds a JSONPatch policy targeting a SlurmCluster.
func policy(name string, priority int32, patches ...slurmv1alpha1.ResourcePatch) slurmv1alpha1.ResourcePatchPolicy {
	return slurmv1alpha1.ResourcePatchPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: "default"},
		Spec: slurmv1alpha1.ResourcePatchPolicySpec{
			TargetRef: slurmv1alpha1.PolicyTargetReference{
				Group: "slurm.nebius.ai",
				Kind:  "SlurmCluster",
				Name:  "my-cluster",
			},
			Priority: ptr.To(priority),
			Type:     slurmv1alpha1.JSONPatchType,
			Patches:  patches,
		},
	}
}

func nameSel(kind, name string) slurmv1alpha1.ResourceSelector {
	return slurmv1alpha1.ResourceSelector{Kind: kind, Name: ptr.To(name)}
}

// representativeStatefulSet mirrors the structure of a controller/worker
// StatefulSet generated by the operator (one main container, labelled pod
// template, immutable selector).
func representativeStatefulSet() *appsv1.StatefulSet {
	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:        "my-cluster-worker",
			Namespace:   "default",
			Labels:      map[string]string{"app.kubernetes.io/component": "worker"},
			Annotations: map[string]string{"existing": "true"},
		},
		Spec: appsv1.StatefulSetSpec{
			Replicas: ptr.To(int32(3)),
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{"app.kubernetes.io/component": "worker"},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels:      map[string]string{"app.kubernetes.io/component": "worker"},
					Annotations: map[string]string{"kubectl.kubernetes.io/default-container": "slurmd"},
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:  "slurmd",
							Image: "slurmd:latest",
							Resources: corev1.ResourceRequirements{
								Limits: corev1.ResourceList{corev1.ResourceCPU: resource.MustParse("500m")},
							},
						},
					},
				},
			},
		},
	}
}

func TestApply_AddPodTemplateAnnotation(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	p := policy("mesh", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{
				Op:    "add",
				Path:  "/spec/template/metadata/annotations/sidecar.istio.io~1inject",
				Value: jsonValue(t, "true"),
			},
		},
	})

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)
	assert.Equal(t, "true", sts.Spec.Template.Annotations["sidecar.istio.io/inject"])
}

func TestApply_ReplaceContainerResourceLimit(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	p := policy("gpu", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{
				Op:    "add",
				Path:  "/spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu",
				Value: jsonValue(t, "8"),
			},
		},
	})

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)

	gpu := sts.Spec.Template.Spec.Containers[0].Resources.Limits["nvidia.com/gpu"]
	assert.Equal(t, "8", gpu.String())
}

func TestApply_AddTolerationToList(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	toleration := corev1.Toleration{
		Key:      "nvidia.com/gpu",
		Operator: corev1.TolerationOpExists,
		Effect:   corev1.TaintEffectNoSchedule,
	}
	p := policy("tol", 0,
		slurmv1alpha1.ResourcePatch{
			ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
			JSONPatch: []slurmv1alpha1.JSONPatchOperation{
				// First ensure the tolerations array exists, then append.
				{Op: "add", Path: "/spec/template/spec/tolerations", Value: jsonValue(t, []corev1.Toleration{})},
				{Op: "add", Path: "/spec/template/spec/tolerations/-", Value: jsonValue(t, toleration)},
			},
		},
	)

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)
	require.Len(t, sts.Spec.Template.Spec.Tolerations, 1)
	assert.Equal(t, "nvidia.com/gpu", sts.Spec.Template.Spec.Tolerations[0].Key)
}

func TestApply_RemoveOpClearsField(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()
	require.Equal(t, "true", sts.Annotations["existing"])

	p := policy("rm", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{Op: "remove", Path: "/metadata/annotations/existing"},
		},
	})

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)
	_, ok := sts.Annotations["existing"]
	assert.False(t, ok, "annotation should have been removed")
}

func TestApply_JSONMergePatch(t *testing.T) {
	scheme := testScheme(t)
	cm := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-cluster-slurm-config",
			Namespace: "default",
		},
		Data: map[string]string{"slurm.conf": "base"},
	}

	p := slurmv1alpha1.ResourcePatchPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "merge", Namespace: "default"},
		Spec: slurmv1alpha1.ResourcePatchPolicySpec{
			TargetRef: slurmv1alpha1.PolicyTargetReference{
				Group: "slurm.nebius.ai", Kind: "SlurmCluster", Name: "my-cluster",
			},
			Type: slurmv1alpha1.JSONMergePatchType,
			Patches: []slurmv1alpha1.ResourcePatch{
				{
					ResourceRef: nameSel("ConfigMap", "my-cluster-slurm-config"),
					JSONMergePatch: jsonValue(t, map[string]any{
						"metadata": map[string]any{
							"annotations": map[string]string{"custom-key": "custom-value"},
						},
						"data": map[string]string{"extra.conf": "SomeExtraConfig=value"},
					}),
				},
			},
		},
	}

	results, err := resourcepatch.Apply(scheme, cm, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)
	assert.Equal(t, "custom-value", cm.Annotations["custom-key"])
	assert.Equal(t, "SomeExtraConfig=value", cm.Data["extra.conf"])
	assert.Equal(t, "base", cm.Data["slurm.conf"], "merge patch must preserve existing keys")
}

func TestApply_ExactNameSelector(t *testing.T) {
	scheme := testScheme(t)

	tests := []struct {
		name     string
		selector string
		objName  string
		want     bool
	}{
		{"exact match", "my-cluster-worker", "my-cluster-worker", true},
		{"exact mismatch", "my-cluster-worker", "my-cluster-login", false},
		// Glob patterns are not interpreted: they only match a literal name.
		{"glob is treated literally", "my-cluster-worker-*", "my-cluster-worker-0", false},
		{"glob literal exact", "my-cluster-worker-*", "my-cluster-worker-*", true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			sts := representativeStatefulSet()
			sts.Name = tt.objName
			p := policy("p", 0, slurmv1alpha1.ResourcePatch{
				ResourceRef: slurmv1alpha1.ResourceSelector{Kind: "StatefulSet", Name: ptr.To(tt.selector)},
				JSONPatch: []slurmv1alpha1.JSONPatchOperation{
					{Op: "add", Path: "/metadata/annotations/patched", Value: jsonValue(t, "yes")},
				},
			})
			results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
			require.NoError(t, err)
			if tt.want {
				require.Len(t, results, 1)
				assert.True(t, results[0].Applied)
				assert.Equal(t, "yes", sts.Annotations["patched"])
			} else {
				assert.Empty(t, results, "selector should not have matched")
				_, ok := sts.Annotations["patched"]
				assert.False(t, ok)
			}
		})
	}
}

func TestApply_EmptyNameSelectorMatchesAllOfKind(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()
	sts.Name = "anything"

	p := policy("p", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: slurmv1alpha1.ResourceSelector{Kind: "StatefulSet"}, // no NameSelector
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{Op: "add", Path: "/metadata/annotations/patched", Value: jsonValue(t, "yes")},
		},
	})
	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied)
}

func TestApply_KindMismatchSkipped(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	p := policy("p", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("Service", "my-cluster-worker"), // wrong kind for a StatefulSet
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{Op: "add", Path: "/metadata/annotations/patched", Value: jsonValue(t, "yes")},
		},
	})
	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	assert.Empty(t, results)
}

func TestApply_APIVersionSelector(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	mkPolicy := func(apiVersion string) slurmv1alpha1.ResourcePatchPolicy {
		return policy("p", 0, slurmv1alpha1.ResourcePatch{
			ResourceRef: slurmv1alpha1.ResourceSelector{
				Kind:       "StatefulSet",
				Name:       ptr.To("my-cluster-worker"),
				APIVersion: ptr.To(apiVersion),
			},
			JSONPatch: []slurmv1alpha1.JSONPatchOperation{
				{Op: "add", Path: "/metadata/annotations/patched", Value: jsonValue(t, "yes")},
			},
		})
	}

	t.Run("matching apiVersion", func(t *testing.T) {
		obj := representativeStatefulSet()
		results, err := resourcepatch.Apply(scheme, obj, []slurmv1alpha1.ResourcePatchPolicy{mkPolicy("apps/v1")})
		require.NoError(t, err)
		require.Len(t, results, 1)
		assert.True(t, results[0].Applied)
	})

	t.Run("mismatching apiVersion", func(t *testing.T) {
		results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{mkPolicy("apps/v1beta1")})
		require.NoError(t, err)
		assert.Empty(t, results)
	})
}

func TestApply_PriorityOrdering(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	// Two policies write the same annotation; the higher-priority number is
	// applied last and therefore wins.
	low := policy("a-low", 5, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{Op: "add", Path: "/metadata/annotations/winner", Value: jsonValue(t, "low")},
		},
	})
	high := policy("z-high", 10, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			{Op: "add", Path: "/metadata/annotations/winner", Value: jsonValue(t, "high")},
		},
	})

	// Pass them out of order to prove sorting happens inside Apply.
	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{high, low})
	require.NoError(t, err)
	require.Len(t, results, 2)
	assert.Equal(t, "high", sts.Annotations["winner"])
}

func TestApply_EqualPriorityAlphabeticalTiebreak(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	first := policy("aaa", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch:   []slurmv1alpha1.JSONPatchOperation{{Op: "add", Path: "/metadata/annotations/winner", Value: jsonValue(t, "aaa")}},
	})
	second := policy("bbb", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch:   []slurmv1alpha1.JSONPatchOperation{{Op: "add", Path: "/metadata/annotations/winner", Value: jsonValue(t, "bbb")}},
	})

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{second, first})
	require.NoError(t, err)
	require.Len(t, results, 2)
	assert.Equal(t, "bbb", sts.Annotations["winner"], "later alphabetical name applied last")
}

func TestApply_FailedPatchDoesNotMutateAndOthersContinue(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	p := policy("mixed", 0,
		slurmv1alpha1.ResourcePatch{
			ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
			// "test" op against a non-matching value fails.
			JSONPatch: []slurmv1alpha1.JSONPatchOperation{
				{Op: "test", Path: "/metadata/name", Value: jsonValue(t, "wrong-name")},
			},
		},
		slurmv1alpha1.ResourcePatch{
			ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
			JSONPatch: []slurmv1alpha1.JSONPatchOperation{
				{Op: "add", Path: "/metadata/annotations/good", Value: jsonValue(t, "yes")},
			},
		},
	)

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 2)
	assert.False(t, results[0].Applied)
	assert.NotEmpty(t, results[0].Message)
	assert.True(t, results[1].Applied, "message: %s", results[1].Message)
	assert.Equal(t, "yes", sts.Annotations["good"])
	assert.Equal(t, "my-cluster-worker", sts.Name, "failed patch must not have mutated the object")
}

func TestApply_InvalidPolicyDoesNotMutate(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	// Invalid: JSONPatch type but the entry also carries a merge payload, which
	// ValidatePolicy rejects. The valid-looking JSONPatch must NOT be applied.
	p := policy("invalid", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef:    nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch:      []slurmv1alpha1.JSONPatchOperation{{Op: "add", Path: "/metadata/annotations/x", Value: jsonValue(t, "y")}},
		JSONMergePatch: jsonValue(t, map[string]any{"metadata": map[string]any{}}),
	})

	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.False(t, results[0].Applied)
	assert.Contains(t, results[0].Message, "failed validation")
	_, ok := sts.Annotations["x"]
	assert.False(t, ok, "invalid policy must not mutate the object")
}

func TestApply_BadPathReportedAsFailure(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	p := policy("bad", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
		JSONPatch: []slurmv1alpha1.JSONPatchOperation{
			// "replace" requires the target path to exist.
			{Op: "replace", Path: "/spec/template/spec/containers/5/image", Value: jsonValue(t, "x")},
		},
	})
	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.False(t, results[0].Applied)
	assert.NotEmpty(t, results[0].Message)
}

func TestApply_ProtectedFields(t *testing.T) {
	scheme := testScheme(t)

	tests := []struct {
		name string
		op   slurmv1alpha1.JSONPatchOperation
	}{
		{
			name: "name",
			op:   slurmv1alpha1.JSONPatchOperation{Op: "replace", Path: "/metadata/name", Value: jsonValue(t, "renamed")},
		},
		{
			name: "namespace",
			op:   slurmv1alpha1.JSONPatchOperation{Op: "replace", Path: "/metadata/namespace", Value: jsonValue(t, "other")},
		},
		{
			name: "ownerReferences",
			op: slurmv1alpha1.JSONPatchOperation{Op: "add", Path: "/metadata/ownerReferences", Value: jsonValue(t, []metav1.OwnerReference{
				{APIVersion: "v1", Kind: "Pod", Name: "x", UID: "123"},
			})},
		},
		{
			name: "selector",
			op: slurmv1alpha1.JSONPatchOperation{Op: "replace", Path: "/spec/selector/matchLabels", Value: jsonValue(t, map[string]string{
				"app.kubernetes.io/component": "hijacked",
			})},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			sts := representativeStatefulSet()
			p := policy("protected", 0, slurmv1alpha1.ResourcePatch{
				ResourceRef: nameSel("StatefulSet", "my-cluster-worker"),
				JSONPatch:   []slurmv1alpha1.JSONPatchOperation{tt.op},
			})
			results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
			require.NoError(t, err)
			require.Len(t, results, 1)
			assert.False(t, results[0].Applied, "protected field %s must be rejected", tt.name)
			assert.NotEmpty(t, results[0].Message)
			// The object must be unchanged.
			assert.Equal(t, "my-cluster-worker", sts.Name)
			assert.Equal(t, "default", sts.Namespace)
			assert.Empty(t, sts.OwnerReferences)
			assert.Equal(t, "worker", sts.Spec.Selector.MatchLabels["app.kubernetes.io/component"])
		})
	}
}

func TestApply_TypeMismatchEmptyPatchReported(t *testing.T) {
	scheme := testScheme(t)
	sts := representativeStatefulSet()

	// Policy type is JSONPatch but the entry only carries a merge patch.
	p := policy("empty", 0, slurmv1alpha1.ResourcePatch{
		ResourceRef:    nameSel("StatefulSet", "my-cluster-worker"),
		JSONMergePatch: jsonValue(t, map[string]any{"metadata": map[string]any{}}),
	})
	results, err := resourcepatch.Apply(scheme, sts, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.False(t, results[0].Applied)
	assert.Contains(t, results[0].Message, "jsonPatch is empty")
}

func TestFilterPoliciesForTarget(t *testing.T) {
	mk := func(name, ns string, refKind, refName string, refNS *string) slurmv1alpha1.ResourcePatchPolicy {
		return slurmv1alpha1.ResourcePatchPolicy{
			ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: ns},
			Spec: slurmv1alpha1.ResourcePatchPolicySpec{
				TargetRef: slurmv1alpha1.PolicyTargetReference{
					Group: "slurm.nebius.ai", Kind: refKind, Name: refName, Namespace: refNS,
				},
			},
		}
	}

	policies := []slurmv1alpha1.ResourcePatchPolicy{
		mk("match-same-ns", "hpc", "SlurmCluster", "gpu", nil),
		mk("wrong-kind", "hpc", "NodeSet", "gpu", nil),
		mk("wrong-name", "hpc", "SlurmCluster", "other", nil),
		mk("explicit-ns", "default", "SlurmCluster", "gpu", ptr.To("hpc")),
		mk("explicit-other-ns", "default", "SlurmCluster", "gpu", ptr.To("elsewhere")),
	}

	got := resourcepatch.FilterPoliciesForTarget(policies, "slurm.nebius.ai", "SlurmCluster", "gpu", "hpc")
	var names []string
	for _, p := range got {
		names = append(names, p.Name)
	}
	assert.ElementsMatch(t, []string{"match-same-ns", "explicit-ns"}, names)
}

func TestApply_NodeConfiguratorTargetGenericKind(t *testing.T) {
	// The engine itself is agnostic to the target kind; matching is by the
	// generated resource's kind. This proves a DaemonSet is patchable.
	scheme := testScheme(t)
	ds := &appsv1.DaemonSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "node-configurator",
			Namespace: "default",
		},
		Spec: appsv1.DaemonSetSpec{
			Selector: &metav1.LabelSelector{MatchLabels: map[string]string{"app": "nc"}},
			UpdateStrategy: appsv1.DaemonSetUpdateStrategy{
				Type: appsv1.RollingUpdateDaemonSetStrategyType,
				RollingUpdate: &appsv1.RollingUpdateDaemonSet{
					MaxUnavailable: ptr.To(intstr.FromInt32(1)),
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: map[string]string{"app": "nc"}},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{{Name: "configurator", Image: "nc:latest"}},
				},
			},
		},
	}

	p := slurmv1alpha1.ResourcePatchPolicy{
		ObjectMeta: metav1.ObjectMeta{Name: "nc", Namespace: "default"},
		Spec: slurmv1alpha1.ResourcePatchPolicySpec{
			TargetRef: slurmv1alpha1.PolicyTargetReference{Group: "slurm.nebius.ai", Kind: "NodeConfigurator", Name: "node-configurator"},
			Type:      slurmv1alpha1.JSONPatchType,
			Patches: []slurmv1alpha1.ResourcePatch{{
				ResourceRef: nameSel("DaemonSet", "node-configurator"),
				JSONPatch: []slurmv1alpha1.JSONPatchOperation{
					{Op: "add", Path: "/spec/template/spec/containers/0/resources", Value: jsonValue(t, corev1.ResourceRequirements{
						Limits: corev1.ResourceList{corev1.ResourceMemory: mustQuantity("512Mi")},
					})},
				},
			}},
		},
	}

	results, err := resourcepatch.Apply(scheme, ds, []slurmv1alpha1.ResourcePatchPolicy{p})
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Applied, "message: %s", results[0].Message)
	mem := ds.Spec.Template.Spec.Containers[0].Resources.Limits[corev1.ResourceMemory]
	assert.Equal(t, "512Mi", mem.String())
}

// ensure client.Object is satisfied by the test objects (compile-time guard).
var _ client.Object = (*appsv1.StatefulSet)(nil)
var _ client.Object = (*appsv1.DaemonSet)(nil)
