/*
Copyright 2024 Nebius B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package resourcepatch implements the in-memory patching engine used by the
// ResourcePatchPolicy feature. It applies RFC 6902 (JSON Patch) and RFC 7386
// (JSON Merge Patch) operations to Kubernetes objects generated by the operator
// before they are submitted to the API server.
package resourcepatch

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"

	jsonpatch "github.com/evanphx/json-patch/v5"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/apiutil"

	slurmv1alpha1 "nebius.ai/slurm-operator/api/v1alpha1"
)

// Result describes the outcome of applying a single policy patch entry to one
// object.
type Result struct {
	// PolicyName / PolicyNamespace identify the source policy.
	PolicyName      string
	PolicyNamespace string

	// Resource identifies the object the patch targeted.
	Resource corev1.ObjectReference

	// Applied reports whether the patch was applied to the object.
	Applied bool

	// Message provides human-readable details, typically on failure.
	Message string
}

// Apply applies all matching patches from policies to obj in place.
//
// policies must already be filtered to those whose targetRef points at obj's
// parent (see FilterPoliciesForTarget). Policies are applied in ascending
// priority order, with namespace/name used as a deterministic tiebreaker.
//
// A patch that fails (bad path, protected-field violation, malformed payload)
// leaves obj untouched for that entry and is reported as a non-applied Result;
// the remaining patches still run. The returned error is non-nil only for
// problems that prevent matching altogether (e.g. unknown object type).
func Apply(
	scheme *runtime.Scheme,
	obj client.Object,
	policies []slurmv1alpha1.ResourcePatchPolicy,
) ([]Result, error) {
	gvk, err := apiutil.GVKForObject(obj, scheme)
	if err != nil {
		return nil, fmt.Errorf("resolving GVK for object: %w", err)
	}
	kind := gvk.Kind
	apiVersion := gvk.GroupVersion().String()
	name := obj.GetName()

	sorted := sortPolicies(policies)

	var results []Result
	for i := range sorted {
		policy := &sorted[i]
		for j := range policy.Spec.Patches {
			patch := &policy.Spec.Patches[j]
			if !matchSelector(patch.ResourceRef, kind, apiVersion, name) {
				continue
			}
			res := applyOne(obj, policy, patch, kind, apiVersion)
			results = append(results, res)
		}
	}
	return results, nil
}

// FilterPoliciesForTarget returns the subset of policies whose targetRef points
// at the parent identified by group/kind/name/namespace. A policy with an empty
// targetRef namespace defaults to the policy's own namespace.
func FilterPoliciesForTarget(
	policies []slurmv1alpha1.ResourcePatchPolicy,
	group, kind, name, namespace string,
) []slurmv1alpha1.ResourcePatchPolicy {
	var out []slurmv1alpha1.ResourcePatchPolicy
	for i := range policies {
		ref := policies[i].Spec.TargetRef
		targetNS := policies[i].Namespace
		if ref.Namespace != nil && *ref.Namespace != "" {
			targetNS = *ref.Namespace
		}
		if ref.Group == group && ref.Kind == kind && ref.Name == name && targetNS == namespace {
			out = append(out, policies[i])
		}
	}
	return out
}

func applyOne(
	obj client.Object,
	policy *slurmv1alpha1.ResourcePatchPolicy,
	patch *slurmv1alpha1.ResourcePatch,
	kind, apiVersion string,
) Result {
	res := Result{
		PolicyName:      policy.Name,
		PolicyNamespace: policy.Namespace,
		Resource: corev1.ObjectReference{
			APIVersion: apiVersion,
			Kind:       kind,
			Name:       obj.GetName(),
			Namespace:  obj.GetNamespace(),
		},
	}

	original, err := json.Marshal(obj)
	if err != nil {
		res.Message = fmt.Sprintf("marshalling object: %v", err)
		return res
	}

	patched, err := runPatch(policy.Spec.Type, patch, original)
	if err != nil {
		res.Message = err.Error()
		return res
	}

	if violation := protectedFieldViolation(original, patched); violation != "" {
		res.Message = violation
		return res
	}

	if err := resetAndUnmarshal(obj, patched); err != nil {
		res.Message = fmt.Sprintf("decoding patched object: %v", err)
		return res
	}

	res.Applied = true
	return res
}

func runPatch(
	patchType slurmv1alpha1.PatchType,
	patch *slurmv1alpha1.ResourcePatch,
	doc []byte,
) ([]byte, error) {
	switch patchType {
	case slurmv1alpha1.JSONPatchType:
		if len(patch.JSONPatch) == 0 {
			return nil, fmt.Errorf("policy type is JSONPatch but jsonPatch is empty")
		}
		raw, err := json.Marshal(patch.JSONPatch)
		if err != nil {
			return nil, fmt.Errorf("marshalling jsonPatch: %w", err)
		}
		decoded, err := jsonpatch.DecodePatch(raw)
		if err != nil {
			return nil, fmt.Errorf("decoding jsonPatch: %w", err)
		}
		patched, err := decoded.Apply(doc)
		if err != nil {
			return nil, fmt.Errorf("applying jsonPatch: %w", err)
		}
		return patched, nil

	case slurmv1alpha1.JSONMergePatchType:
		if patch.JSONMergePatch == nil || len(patch.JSONMergePatch.Raw) == 0 {
			return nil, fmt.Errorf("policy type is JSONMergePatch but jsonMergePatch is empty")
		}
		patched, err := jsonpatch.MergePatch(doc, patch.JSONMergePatch.Raw)
		if err != nil {
			return nil, fmt.Errorf("applying jsonMergePatch: %w", err)
		}
		return patched, nil

	default:
		return nil, fmt.Errorf("unsupported patch type %q", patchType)
	}
}

// matchSelector reports whether ref matches a resource of the given kind,
// apiVersion and name. Name matching is exact; an empty Name matches every
// resource of the kind.
func matchSelector(ref slurmv1alpha1.ResourceSelector, kind, apiVersion, name string) bool {
	if ref.Kind != kind {
		return false
	}
	if ref.APIVersion != nil && *ref.APIVersion != "" && *ref.APIVersion != apiVersion {
		return false
	}
	if ref.Name == nil || *ref.Name == "" {
		return true
	}
	return *ref.Name == name
}

func sortPolicies(policies []slurmv1alpha1.ResourcePatchPolicy) []slurmv1alpha1.ResourcePatchPolicy {
	sorted := make([]slurmv1alpha1.ResourcePatchPolicy, len(policies))
	copy(sorted, policies)
	sort.SliceStable(sorted, func(i, j int) bool {
		pi, pj := priorityOf(&sorted[i]), priorityOf(&sorted[j])
		if pi != pj {
			return pi < pj
		}
		if sorted[i].Namespace != sorted[j].Namespace {
			return sorted[i].Namespace < sorted[j].Namespace
		}
		return sorted[i].Name < sorted[j].Name
	})
	return sorted
}

func priorityOf(policy *slurmv1alpha1.ResourcePatchPolicy) int32 {
	if policy.Spec.Priority == nil {
		return 0
	}
	return *policy.Spec.Priority
}

// resetAndUnmarshal replaces the contents of obj with the decoded JSON document.
// obj is zeroed first so that fields removed by the patch are cleared rather
// than retained from the pre-patch state.
func resetAndUnmarshal(obj client.Object, data []byte) error {
	v := reflect.ValueOf(obj)
	if v.Kind() != reflect.Ptr || v.IsNil() {
		return fmt.Errorf("object must be a non-nil pointer, got %T", obj)
	}
	elem := v.Elem()
	elem.Set(reflect.Zero(elem.Type()))
	return json.Unmarshal(data, obj)
}
