---

- name: Ensure SquashFS FUSE support is installed
  ansible.builtin.apt:
    name:
      - squashfuse
      - fuse3
      - libfuse3-3
    state: present
    update_cache: true
  tags:
    - squashfuse
