{
 "title": "Cluster Health & Overview",
 "tags": [
  "nebius",
  "soperator",
  "overview",
  "cluster"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "o11y", "label": "O11y" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_os_info, cluster)"
    }
   },
   {
    "name": "nodeset",
    "label": "Nodeset",
    "query": {
     "query": "label_values(slurm_node_info{cluster=~\"$cluster\"},nodeset_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Worker Node",
    "query": {
     "query": "label_values(slurm_node_info{cluster=~\"$cluster\", nodeset_name=~\"$nodeset\"}, node_name)"
    }
   },
   {
    "name": "user_name",
    "label": "Job Username",
    "query": {
     "query": "label_values(slurm_job_info{cluster=~\"$cluster\"},user_name)"
    }
   },
   {
    "name": "partition_match_exp",
    "label": "System Jobs",
    "query": "Show : =~\"^.*$\",Hide : !~\"^(hidden|background)$\""
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Soperator Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(\n    kube_customresource_slurmcluster_info{cluster=~\"$cluster\", \n        cr_version!=\"\"\n    }\n) by(cr_version)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Project ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  cadvisor_version_info{cluster=~\"$cluster\"}\n) by(iam_project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(\n    kube_node_labels{cluster=~\"$cluster\", label_nebius_com_gpu_name!=\"\"}\n) by (label_nebius_com_gpu_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "GPU Nodes",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  slurm_node_info{cluster=~\"$cluster\"\n}\n) by()"
    }
   ]
  },
  {
   "title": "Last Soperator upgrade",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  tlast_change_over_time(\n    (\n      group(\n        kube_customresource_slurmcluster_info{cluster=~\"$cluster\", \n          cr_version!=\"\"\n        }\n      ) by(cr_version)\n    )[180d]\n  )\n    *\n  1000\n)\nand on(cr_version)\ngroup(\n  kube_customresource_slurmcluster_info{cluster=~\"$cluster\", \n    cr_version!=\"\"\n  }\n) by(cr_version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "mk8s ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  cadvisor_version_info{cluster=~\"$cluster\"}\n) by(mk8s_cluster_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n    \n  }\n) by()"
    }
   ]
  },
  {
   "title": "NVLink Groups",
   "type": "stat",
   "description": "For GB platform only",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(slurm_node_nvlink_instance_group{cluster=~\"$cluster\"}) by (cluster, nvlink_instance_group)\n) by (cluster)"
    }
   ]
  },
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cluster Utilization 1d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        \n    }\n        >=\n    10\n)[1d:10m])\n/\nsum_over_time(\n    count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        \n    }\n)[1d:10m])\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Job Size",
   "type": "stat",
   "description": "Based on number of nodes per job (nodes > 1)\n\nOver the selected time window",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  (\n    count(\n      slurm_node_job{cluster=~\"$cluster\"\n        \n      }\n    ) by(job_id)\n      * on(job_id)\n    slurm_job_info{cluster=~\"$cluster\", \n      \n      slurm_partition${partition_match_exp}\n    }\n  )\n    >\n  1\n) by ()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Power Usage",
   "type": "stat",
   "description": "Over the selected time window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\"\n    \n  }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n      \n    }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    slurm_node_info{cluster=~\"$cluster\", \n        \n        state_base=~\"IDLE|MIXED|ALLOCATED\",\n        state_is_drain=\"false\"\n    }\n) by ()\n"
    }
   ]
  },
  {
   "title": "SlurmCtld Pod Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_created{cluster=~\"$cluster\", \n  \n  namespace=~\"soperator\",\n  pod=~\"controller-[0-9]+\"\n}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Unavailable Time",
   "type": "stat",
   "description": "Time nodes are in states where new jobs cannot be started on them",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_avg(sum(increase(slurm_node_unavailability_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Cluster Utilization 7d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        \n    }\n        >=\n    10\n)[7d:1h])\n/\nsum_over_time(\n    count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n           }\n)[7d:1h])\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Job Duration",
   "type": "stat",
   "description": "Based on number of nodes per job\n\nOver the selected time window",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum_over_time(\n    (\n      slurm_job_info{cluster=~\"$cluster\", \n        \n        slurm_partition${partition_match_exp},\n        job_state=\"RUNNING\"\n      }\n    )[1d:1m]\n  )\n    *\n  60\n) by ()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg GPU Util",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "with (\n  filters = {}\n)\navg(\n  DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", filters}\n)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    slurm_node_info{cluster=~\"$cluster\", \n        \n        state_base=~\"DOWN|ERROR\",\n        state_is_drain=\"true\"\n    }\n) by ()\n"
    }
   ]
  },
  {
   "title": "Total Node Failures",
   "type": "stat",
   "description": "In selected time window",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(max by(node_name, reason, state_base, state_is_drain, state_is_maintenance, state_is_reserved) (slurm_node_fails_total{cluster=~\"$cluster\", state_is_maintenance=\"false\", })[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Draining Time",
   "type": "stat",
   "description": "Time nodes spent in `draining` state",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_avg(sum(increase(slurm_node_draining_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "with (\n  filters = {}\n)\ncount(\n  slurm_job_info{cluster=~\"$cluster\", \n    filters,\n    job_state=\"RUNNING\",\n    slurm_partition${partition_match_exp},\n  }\n)"
    }
   ]
  },
  {
   "title": "Allocated Nodes",
   "type": "stat",
   "description": "GPU Nodes",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  slurm_node_info{cluster=~\"$cluster\", state_base=\"ALLOCATED\"}\n) by(cluster)"
    }
   ]
  },
  {
   "title": "Overall MTBF (7d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "GPUh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum (\n    increase(\n      sum by (node_name, state_base, state_is_drain, state_is_maintenance, state_is_reserved) (\n        slurm_node_gpu_seconds_total{cluster=~\"$cluster\", \n          \n          state_is_maintenance=\"false\",\n          state_base=~\".*\"\n        }\n      )[7d]\n    )\n  )\n  /\n  (\n    sum (\n      increase(\n        max by (node_name, reason, state_base, state_is_drain, state_is_maintenance, state_is_reserved) (\n          slurm_node_fails_total{cluster=~\"$cluster\", \n            \n            state_is_maintenance=\"false\"\n          }\n        )[7d]\n      )\n    )\n    or\n    (\n      sum (\n        increase(\n          slurm_node_gpu_seconds_total{cluster=~\"$cluster\", \n            \n            state_is_maintenance=\"false\",\n            state_base=~\".*\"\n          }[7d]\n        )\n      ) * 0\n    )\n  )\n) / 3600",
     "legendFormat": "cluster = $cluster"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cluster Utilization",
   "type": "timeseries",
   "description": "Proportion of GPUs with at least 10% utilization to total",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        }\n      >=\n    10\n  ) by(cluster)\n    /\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        }\n  ) by(cluster)\n)\n  *\n100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MTBF Trend (7d rolling window)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum (\n    increase(\n      sum by (node_name, state_base, state_is_drain, state_is_maintenance, state_is_reserved) (\n        slurm_node_gpu_seconds_total{cluster=~\"$cluster\", \n          state_is_maintenance=\"false\",\n        }\n      )[7d]\n    )\n  )\n  /\n  (\n    sum (\n      increase(\n        max by (node_name, reason, state_base, state_is_drain, state_is_maintenance, state_is_reserved) (\n          slurm_node_fails_total{cluster=~\"$cluster\", \n            state_is_maintenance=\"false\"\n          }\n        )[7d]\n      )\n    )\n    or\n    (\n      sum (\n        increase(\n          slurm_node_gpu_seconds_total{cluster=~\"$cluster\", \n            state_is_maintenance=\"false\",\n          }[7d]\n        )\n      ) * 0\n    )\n  )\n) / 36",
     "legendFormat": "MTBF"
    }
   ]
  },
  {
   "title": "Cluster Power usage",
   "type": "timeseries",
   "description": "Only for GPUs with at least 10% utilization",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\"\n    }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\"\n      }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)",
     "legendFormat": "avg"
    },
    {
     "expr": "min(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\"\n    }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"\n        }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "description": "Jobs in `PENDING` state by reason",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  slurm_job_info{cluster=~\"$cluster\", \n    slurm_partition${partition_match_exp},\n    job_state=\"PENDING\"\n  }\n) by(job_state_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster SM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  DCGM_FI_PROF_SM_ACTIVE{cluster=~\"$cluster\"}\n)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(\n  DCGM_FI_PROF_SM_ACTIVE{cluster=~\"$cluster\"}\n)",
     "legendFormat": "avg"
    },
    {
     "expr": "min(\n  DCGM_FI_PROF_SM_ACTIVE{cluster=~\"$cluster\"}\n)",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes by Categories",
     "type": "timeseries",
     "description": "Node categories are mutually exclusive:\n- Other/error: ERROR, NOT_RESPONDING, INVALID (invalid registration), or FAIL; these conditions take precedence over all other categories. Also includes otherwise unclassified nodes.\n- Powered down: DOWN, POWERED_DOWN, POWER_UP, or POWERING_UP, unless an Other/error error condition is present. This grouping does not imply every node is physically powered off.\n- Maintenance: Nodes marked for maintenance, excluding the error and powered-down conditions above.\n- Draining: Nodes with DRAIN and allocated resources (ALLOCATED or MIXED) or unfinished job cleanup (COMPLETING), excluding the conditions above.\n- Drained: IDLE nodes with DRAIN, no COMPLETING, and none of the conditions above.\n- Busy: Nodes with allocated resources or unfinished job cleanup, without DRAIN and none of the conditions above.\n- Idle: IDLE nodes without COMPLETING or DRAIN and none of the conditions above. Includes reserved and planned nodes; does not guarantee eligibility for every job.\nCLOUD, RESERVED, PLANNED, POWER_DOWN, POWERING_DOWN, and POWER_DRAIN do not determine the category.\n\nNodes by Categories and Nodes by State use the same category definitions and the same bottom-to-top stacking order: Busy → Draining → Idle → Drained → Other/error → Maintenance → Powered down. Nodes by Categories shows totals per category; Nodes by State breaks each category down into exact state combinations.\n\nNodes by Categories uses query order (A–G) for its series and bottom-to-top stacking order. It does not use numbering prefixes or ordering transformations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base=~\"ALLOCATED|MIXED\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_drain!=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!~\"DOWN|ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_drain!=\"true\", state_is_completing=\"true\"})",
       "legendFormat": "Busy"
      },
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base=~\"ALLOCATED|MIXED\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_drain=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!~\"DOWN|ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_drain=\"true\", state_is_completing=\"true\"})",
       "legendFormat": "Draining"
      },
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base=\"IDLE\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_drain!=\"true\", state_is_completing!=\"true\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base=\"IDLE\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_drain=\"true\", state_is_completing!=\"true\"})",
       "legendFormat": "Drained"
      },
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base=\"ERROR\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_is_not_responding=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_is_invalid=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_is_fail=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!~\"IDLE|ALLOCATED|MIXED|DOWN|ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance!=\"true\", state_is_completing!=\"true\"})",
       "legendFormat": "Other/error"
      },
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!~\"DOWN|ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down!=\"true\", state_is_power_up!=\"true\", state_is_powering_up!=\"true\", state_is_maintenance=\"true\"})",
       "legendFormat": "Maintenance"
      },
      {
       "expr": "count(slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base=\"DOWN\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!=\"ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powered_down=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!=\"ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_power_up=\"true\"} or slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\", state_base!=\"ERROR\", state_is_not_responding!=\"true\", state_is_invalid!=\"true\", state_is_fail!=\"true\", state_is_powering_up=\"true\"})",
       "legendFormat": "Powered down"
      }
     ]
    },
    {
     "title": "Nodes by State",
     "type": "timeseries",
     "description": "Node counts by exact Slurm scheduling state and exported flags, grouped by the same categories as Nodes by Categories. Legends include the category followed by the native state combination.\nERROR, NOT_RESPONDING, INVALID (invalid registration), and FAIL take precedence and map to Other/error. Otherwise DOWN, POWERED_DOWN, POWER_UP, and POWERING_UP map to Powered down. POWER_DOWN and POWERING_DOWN do not determine the category.\n\nNodes by Categories and Nodes by State use the same category definitions and the same bottom-to-top stacking order: Busy → Draining → Idle → Drained → Other/error → Maintenance → Powered down. Nodes by Categories shows totals per category; Nodes by State breaks each category down into exact state combinations.\n\nColors share the category palette. Busy MIXED nodes use lighter blue than ALLOCATED; the exact MIXED+CLOUD combination uses an intermediate blue. Power-up flags use lighter shades; power-down flags use darker shades; base DOWN uses the darkest shade. COMPLETING in Busy/Draining and RESERVED/PLANNED in Idle use slightly darker shades. Power shading takes precedence over these details, and base DOWN takes precedence over all other shading. Unmatched series are bright pink.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (state_base, state_is_cloud, state_is_drain, state_is_maintenance, state_is_reserved, state_is_completing, state_is_fail, state_is_planned, state_is_not_responding, state_is_invalid, state_is_power_down, state_is_power_drain, state_is_powered_down, state_is_powering_down, state_is_powering_up, state_is_power_up) (slurm_node_info{node_name=~\"$node_name\", cluster=~\"$cluster\"})",
       "legendFormat": "{{state_base}}+CLOUD={{state_is_cloud}}+DRAIN={{state_is_drain}}+MAINTENANCE={{state_is_maintenance}}+RESERVED={{state_is_reserved}}+COMPLETING={{state_is_completing}}+FAIL={{state_is_fail}}+PLANNED={{state_is_planned}}+NOT_RESPONDING={{state_is_not_responding}}+INVALID={{state_is_invalid}}+POWER_DOWN={{state_is_power_down}}+POWER_DRAIN={{state_is_power_drain}}+POWERED_DOWN={{state_is_powered_down}}+POWERING_DOWN={{state_is_powering_down}}+POWERING_UP={{state_is_powering_up}}+POWER_UP={{state_is_power_up}}"
      }
     ]
    },
    {
     "title": "Node Problems Timeline",
     "type": "state-timeline",
     "description": "Timeline of node problems showing Down (DOWN/ERROR states), Drained (IDLE with drain), and Draining (ALLOCATED/MIXED with drain) states. Maintenance nodes are filtered out.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "with (\n  node_fails = sum by (node_name) (\n      # Down: Nodes in DOWN or ERROR state (not in maintenance)\n      count by (node_name) (slurm_node_info{cluster=~\"$cluster\", state_base=~\"DOWN|ERROR\", state_is_maintenance!=\"true\", node_name=~\"$node_name\", }) * 1 or\n      # Drained: IDLE nodes with drain flag (not in maintenance)\n      count by (node_name) (slurm_node_info{cluster=~\"$cluster\", state_base=\"IDLE\", state_is_drain=\"true\", state_is_maintenance!=\"true\", node_name=~\"$node_name\", }) * 2 or\n      # Draining: ALLOCATED/MIXED nodes with drain flag (not in maintenance)\n      count by (node_name) (slurm_node_info{cluster=~\"$cluster\", state_base=~\"ALLOCATED|MIXED\", state_is_drain=\"true\", state_is_maintenance!=\"true\", node_name=~\"$node_name\", }) * 3\n    )\n)\nnode_fails\nor\n(\n  # To show recovery as IDLE without drain state after failure\n  count by (node_name) (slurm_node_info{cluster=~\"$cluster\", state_base=~\"IDLE\", state_is_drain=\"false\", state_is_maintenance!=\"true\", node_name=~\"$node_name\", }) * 4\n  and\n  min_over_time(node_fails[15m:1m]) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Unavailable Time",
     "type": "timeseries",
     "description": "Time nodes are in states where new jobs cannot be started on them",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(increase(slurm_node_unavailability_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_avg(sum(increase(slurm_node_unavailability_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0, sum(increase(slurm_node_unavailability_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Node Draining Time",
     "type": "timeseries",
     "description": "Time nodes spent in `draining` state",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(increase(slurm_node_draining_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_avg(sum(increase(slurm_node_draining_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0, sum(increase(slurm_node_draining_duration_seconds_bucket{cluster=~\"$cluster\"}[$__rate_interval])) by (le))",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Node Problems Breakdown",
     "type": "table",
     "description": "Lists nodes that are DOWN, in ERROR state, or have DRAIN flag set (maintenance nodes excluded).\n\n**Columns:**\n- Fail Reason: From failure counter metrics\n- State Reason: From node info (Soperator 1.22+)\n\n**Note:** Rows group events by state - same node may appear multiple times with overlapping time ranges.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 244 },
     "targets": [
      {
       "expr": "with (\n  filters = {},\n  running_jobs = group(slurm_job_info{cluster=~\"$cluster\", filters, job_state=~\"RUNNING\"}) by (job_id, job_name),\n  node_fails = (\n    # Get nodes with problems: DOWN/ERROR states or drain flag\n    slurm_node_info{cluster=~\"$cluster\", filters, state_base=~\"DOWN|ERROR\", state_is_maintenance!=\"true\", node_name=~\"$node_name\"} or\n    slurm_node_info{cluster=~\"$cluster\", filters, state_is_drain=\"true\", state_is_maintenance!=\"true\", node_name=~\"$node_name\"}\n  ),\n  node_fails_with_job_id = node_fails * on (node_name) group_left(job_id) slurm_node_job{cluster=~\"$cluster\", filters}\n)\n(\n  node_fails_with_job_id\n  and on (job_id)\n  (\n      running_jobs offset -60m or running_jobs offset 60m\n  )\n)\nor\nnode_fails",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Jobs",
     "type": "table",
     "description": "Jobs in `RUNNING` state at the end of selected time window.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "with (\n  filters = {}\n)\n# Main job info\nslurm_job_info{cluster=~\"$cluster\", \n  filters,\n  job_state=~\"RUNNING\", \n  user_name=~\"$user_name\", \n  slurm_partition${partition_match_exp}, \n}\n* on (job_id) group_left()\ncount by (job_id) (slurm_node_job{cluster=~\"$cluster\", filters})"
      },
      {
       "expr": "with (\n  filters = {}\n)\n# Job duration\nmax by (job_id) (slurm_job_duration_seconds{cluster=~\"$cluster\", filters})\n* on (job_id) group_left()\nslurm_job_info{cluster=~\"$cluster\", \n  filters,\n  job_state=~\"RUNNING\", \n  user_name=~\"$user_name\", \n  slurm_partition${partition_match_exp}, \n}",
       "legendFormat": "__auto"
      },
      {
       "expr": "with (\n  filters = {}\n)\n# GPU Util\navg(\n  slurm_node_job{cluster=~\"$cluster\"}\n  * on(cluster, node_name) group_left()\n  avg(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", filters}\n  ) by (cluster, node_name)\n) by (job_id)\nand on (job_id)\nslurm_job_info{cluster=~\"$cluster\",\n  filters,\n  job_state=\"RUNNING\",\n  user_name=~\"$user_name\",\n  slurm_partition${partition_match_exp},\n}",
       "legendFormat": "__auto"
      },
      {
       "expr": "with (\n  filters = {}\n)\n# SM Util\navg(\n  slurm_node_job{cluster=~\"$cluster\"}\n  * on(cluster, node_name) group_left()\n  avg(\n    DCGM_FI_PROF_SM_ACTIVE{cluster=~\"$cluster\", filters}\n  ) by (cluster, node_name)\n) by (job_id)\nand on (job_id)\nslurm_job_info{cluster=~\"$cluster\",\n  filters,\n  job_state=\"RUNNING\",\n  user_name=~\"$user_name\",\n  slurm_partition${partition_match_exp},\n}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful Jobs %",
     "type": "timeseries",
     "description": "For jobs with at least 4 nodes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  sum(\n    slurm_job_info{cluster=~\"$cluster\", \n      \n      slurm_partition${partition_match_exp},\n      job_state=~\"COMPLETED\"\n    }\n      and on(job_id)\n    (\n      count(\n        slurm_node_job{cluster=~\"$cluster\" }\n      ) by(job_id)\n        >=\n      0\n    )\n  ) by (cluster)\n    /\n  sum(\n    slurm_job_info{cluster=~\"$cluster\", \n      slurm_partition${partition_match_exp},\n      job_state=~\"COMPLETED|FAILED|CANCELLED|TIMEOUT|DEADLINE\",\n    }\n      and on(job_id)\n    (\n      count(\n        slurm_node_job{cluster=~\"$cluster\" }\n      ) by(job_id)\n        >=\n      0\n    )\n  ) by (cluster)\n) \n  *\n100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Size",
     "type": "timeseries",
     "description": "Based on number of nodes per job (nodes > 1)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(\n  (\n    count(\n      slurm_node_job{cluster=~\"$cluster\"\n            }\n    ) by(job_id)\n      * on(job_id)\n    slurm_job_info{cluster=~\"$cluster\", \n      \n      slurm_partition${partition_match_exp}\n    }\n  )\n    >\n  0\n) by()",
       "legendFormat": "max"
      },
      {
       "expr": "avg(\n  (\n    count(\n      slurm_node_job{cluster=~\"$cluster\"\n            }\n    ) by(job_id)\n      * on(job_id)\n    slurm_job_info{cluster=~\"$cluster\", \n      \n      slurm_partition${partition_match_exp}\n    }\n  )\n    >\n  0\n) by()",
       "legendFormat": "avg"
      },
      {
       "expr": "min(\n  (\n    count(\n      slurm_node_job{cluster=~\"$cluster\"\n            }\n    ) by(job_id)\n      * on(job_id)\n    slurm_job_info{cluster=~\"$cluster\", \n      \n      slurm_partition${partition_match_exp}\n    }\n  )\n    >\n  0\n) by()",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Job Duration",
     "type": "timeseries",
     "description": "Excluding system jobs",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(\n  slurm_job_duration_seconds{cluster=~\"$cluster\"}\n  and on(job_id)\n  slurm_job_info{cluster=~\"$cluster\", slurm_partition${partition_match_exp} }\n)",
       "legendFormat": "max"
      },
      {
       "expr": "avg(\n  slurm_job_duration_seconds{cluster=~\"$cluster\" }\n    and on(job_id)\n  slurm_job_info{cluster=~\"$cluster\", slurm_partition${partition_match_exp} }\n)",
       "legendFormat": "avg"
      },
      {
       "expr": "min(\n  slurm_job_duration_seconds{cluster=~\"$cluster\" }\n    and on(job_id)\n  slurm_job_info{cluster=~\"$cluster\", slurm_partition${partition_match_exp} }\n)",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Job Size Distribution",
     "type": "histogram",
     "description": "Over the entire selected range (excluding system jobs)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "targets": [
      {
       "expr": "histogram(\n    count(slurm_node_job{cluster=~\"$cluster\"}) by (job_id)\n    and on(job_id)\n    slurm_job_info{cluster=~\"$cluster\", \n      slurm_partition${partition_match_exp}\n    }\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Jobs with under-utilized workers",
     "type": "state-timeline",
     "description": "% of workers that where not drawing much power when job was in `RUNNING` state\n\nonly jobs with `>=70%` under-utilized workers for more than `20m` are shown",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "with (\n  gpus_total = count(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\"}) by (cluster, node_name),\n  mem_frac = count(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\"} > 2) by (cluster, node_name) / gpus_total,\n  power_frac = count(DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\"} > 120) by (cluster, node_name) / gpus_total,\n  workers_with_mem = round(sum(slurm_node_job{cluster=~\"$cluster\"} * on(cluster, node_name) group_left() mem_frac) by (job_id) > 2),\n  workers_with_power = round(sum(slurm_node_job{cluster=~\"$cluster\"} * on(cluster, node_name) group_left() power_frac) by (job_id) > 2),\n  underutil_pct = (workers_with_mem - workers_with_power) / workers_with_mem * 100,\n  running_jobs = slurm_job_info{cluster=~\"$cluster\", job_state=\"RUNNING\"}\n)\nfloor(avg_over_time(underutil_pct[1h:1m]) >= 70)\nand on(job_id) running_jobs\nand on (job_id)\ncount_over_time( #filter out short durations\n  (avg_over_time(underutil_pct[1h:1m]) > 70 and on(job_id) running_jobs)[1h:1m]\n) > 20",
       "legendFormat": "{{job_id}}"
      }
     ]
    },
    {
     "title": "Job State Timeline",
     "type": "state-timeline",
     "description": "Paginated",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "expr": "with (\n    filters = {slurm_partition${partition_match_exp}},\n)\nsum by (job_id,)(\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"PENDING\", filters}) * 1 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"CONFIGURING\",filters}) * 2 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"RUNNING\", filters}) * 3 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"COMPLETING\", filters}) * 4 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"COMPLETED\", filters}) * 5 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"CANCELLED\", filters}) * 6 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"FAILED\", filters}) * 7 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"TIMEOUT\", filters}) * 8 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"PREEMPTED\", filters}) * 9 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"NODE_FAIL\", filters}) * 10 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"BOOT_FAIL\", filters}) * 11 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"DEADLINE\", filters}) * 12 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"OUT_OF_MEMORY\", filters}) * 13 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"REQUEUED\", filters}) * 14 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"RESIZING\", filters}) * 15 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"SUSPENDED\", filters}) * 16 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"STOPPED\", filters}) * 17 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"POWER_UP_NODE\", filters}) * 18 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"SIGNALING\", filters}) * 19 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"STAGE_OUT\", filters}) * 20 or\n  count by (job_id, job_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"UPDATE_DB\", filters}) * 21\n)",
       "legendFormat": "{{job_id}}"
      }
     ]
    },
    {
     "title": "All Jobs by State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(job_state) (slurm_job_info{cluster=~\"$cluster\", user_name=~\"$user_name\", slurm_partition${partition_match_exp}, })",
       "legendFormat": "{{job_state}}"
      }
     ]
    },
    {
     "title": "Running Jobs by Partition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(slurm_partition) (slurm_job_info{cluster=~\"$cluster\", job_state=\"RUNNING\", user_name=~\"$user_name\", slurm_partition${partition_match_exp}, })",
       "legendFormat": "{{slurm_partition}}"
      }
     ]
    },
    {
     "title": "Finished Jobs",
     "type": "table",
     "description": "Shows jobs in terminal states (COMPLETED, CANCELLED, FAILED, TIMEOUT). All times are displayed in the current Grafana timezone.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 193 },
     "targets": [
      {
       "expr": "with (\n  filters = {}\n)\nslurm_job_info{cluster=~\"$cluster\", \n  filters,\n  job_state=~\"COMPLETED|CANCELLED|FAILED|TIMEOUT\", \n  user_name=~\"$user_name\", \n  slurm_partition${partition_match_exp}, \n}\n* on (job_id) group_left()\ncount by (job_id) (slurm_node_job{cluster=~\"$cluster\", filters}) "
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Jobs by User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(user_name) (slurm_job_info{cluster=~\"$cluster\", job_state=\"RUNNING\", user_name=~\"$user_name\", slurm_partition${partition_match_exp}, })",
       "legendFormat": "{{user_name}}"
      }
     ]
    },
    {
     "title": "All Jobs by User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(user_name) (slurm_job_info{cluster=~\"$cluster\", user_name=~\"$user_name\", slurm_partition${partition_match_exp}, })",
       "legendFormat": "{{user_name}}"
      }
     ]
    },
    {
     "title": "GPU Utilization per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "with (\n  filters = {}\n)\navg(\n  (\n    slurm_node_job{cluster=~\"$cluster\"}\n    * on(cluster, node_name) group_left()\n    avg(\n      DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", filters}\n    ) by (cluster, node_name)\n  )\n  * on (job_id) group_left(user_name)\n  slurm_job_info{cluster=~\"$cluster\",\n    filters,\n    job_state=\"RUNNING\",\n    user_name=~\"$user_name\",\n    slurm_partition${partition_match_exp}\n  }\n) by (user_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "timeseries",
     "description": "Users who have run some jobs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "targets": [
      {
       "expr": "count(\n    count(\n        slurm_job_info{cluster=~\"$cluster\", \n            \n            slurm_partition${partition_match_exp}\n        }\n    ) by (user_name)\n) by ()",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Node Allocation per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "with (\n  filters = {}\n)\ncount(\n  slurm_node_job{cluster=~\"$cluster\", filters}\n  * on (job_id) group_left(user_name)\n  slurm_job_info{cluster=~\"$cluster\", \n    filters,\n    job_state=\"RUNNING\",\n    user_name=~\"$user_name\", \n    slurm_partition${partition_match_exp}\n  }\n) by (user_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}