{
 "title": "NCCL Inspector Raw metrics",
 "tags": [ "nccl-inspector" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "o11y", "label": "O11y" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_os_info, cluster)"
    }
   },
   {
    "name": "jobid",
    "label": "Slurm Job ID",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", slurm_job_id!=\"\"}, slurm_job_id)"
    }
   },
   {
    "name": "hostname",
    "label": "Worker",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", hostname!=\"\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "nccl_algorithm_bandwidth_gbs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "nccl_algorithm_bandwidth_gbs{cluster=~\"$cluster\", hostname=~\"$hostname\", slurm_job_id=~\"$jobid\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  {
   "title": "nccl_bus_bandwidth_gbs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", hostname=~\"$hostname\", slurm_job_id=~\"$jobid\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  {
   "title": "nccl_collective_exec_time_microseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", hostname=~\"$hostname\", slurm_job_id=~\"$jobid\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  {
   "title": "nccl_message_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nccl_message_size_bytes{cluster=~\"$cluster\", hostname=~\"$hostname\", slurm_job_id=~\"$jobid\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  }
 ]
}