{
 "title": "NCCL Inspector metrics",
 "tags": [ "nccl-inspector" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "o11y", "label": "O11y" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_os_info, cluster)"
    }
   },
   {
    "name": "rank",
    "label": "Rank",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", rank!=\"\"}, rank)"
    }
   },
   {
    "name": "n_ranks",
    "label": "N Ranks",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", nranks!=\"\"}, nranks)"
    }
   },
   {
    "name": "collective",
    "label": "Collective",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", collective!=\"\"}, collective)"
    }
   },
   {
    "name": "jobid",
    "label": "Slurm Job ID",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", slurm_job_id!=\"\"}, slurm_job_id)"
    }
   },
   {
    "name": "hostname",
    "label": "Worker",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", __name__=~\"nccl.*\", hostname!=\"\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alg BW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "algbw",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "nccl_algorithm_bandwidth_gbs{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  { "title": "BusBW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "busbw",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"${collective}\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  {
   "title": "busbw",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"}",
     "legendFormat": "{{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B"
    }
   ]
  },
  {
   "title": "busbw",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"}",
     "legendFormat": "{{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B"
    }
   ]
  },
  { "title": "Exec time microseconds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "microseconds <50ms",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"} < 50000",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  {
   "title": "microseconds <50ms",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"} < 50000",
     "legendFormat": "{{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B"
    }
   ]
  },
  {
   "title": "microseconds <50ms",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"} < 50000",
     "legendFormat": "{{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B"
    }
   ]
  },
  {
   "title": "microseconds >50ms",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"} > 50000",
     "legendFormat": "{{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B"
    }
   ]
  },
  { "title": "msg size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "message size",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nccl_message_size_bytes{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  },
  { "title": "seq number", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "seq number",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "nccl_collective_sequence_number{cluster=~\"$cluster\", rank=~\"${rank}\", nranks=~\"${n_ranks}\", collective=~\"$collective\", slurm_job_id=~\"$jobid\", hostname=~\"$hostname\"}",
     "legendFormat": "{{slurm_job_id}}.{{slurm_step_id}} | {{hostname}} [{{hostname_pid}}] / {{n_nodes}} | {{collective}} | R {{rank}}/{{nranks}} | {{message_size_bytes}} B | {{comm_id}}"
    }
   ]
  }
 ]
}