{
 "title": "NFS",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_nfsd_server_threads{namespace=\"nfs-system\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_nfsd_server_threads{namespace=\"nfs-system\"},instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_nfsd_server_threads{instance=~\"$node:(.*)\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NFSd Disk Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_disk_bytes_read_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd bytes read"
    },
    {
     "expr": "rate(node_nfsd_disk_bytes_written_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd bytes written"
    }
   ]
  },
  {
   "title": "NFSd Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_packets_total{proto=\"tcp\",instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "TCP - NFSd network packets (sent+received)"
    },
    {
     "expr": "rate(node_nfsd_packets_total{proto=\"udp\",instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "UDP - NFSd network packets (sent+received)"
    }
   ]
  },
  {
   "title": "NFS Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_read_ahead_cache_not_found_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd read ahead cache not found"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_hits_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache hits (client lost server response)"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_misses_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache an operation that requires caching (idempotent)"
    },
    {
     "expr": "rate(node_nfsd_reply_cache_nocache_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd Reply Cache non-idempotent operations (rename/delete/…)"
    }
   ]
  },
  {
   "title": "NFSd RPC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_rpc_errors_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ error }} - NFSd RPC errors"
    },
    {
     "expr": "rate(node_nfsd_server_rpcs_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "NFSd RPCs"
    }
   ]
  },
  {
   "title": "NFSd Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_connections_total{instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Number of NFSd TCP connections"
    }
   ]
  },
  {
   "title": "NFSd Server Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nfsd_server_threads{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "NFSd kernel threads that are running"
    }
   ]
  },
  {
   "title": "NFSd v3 Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFSd v3 NFSd Requests by Method 1",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_nfsd_requests_total{method='Access',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Commit',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Create',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='FsInfo',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='FsStat',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='GetAttr',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Link',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Lookup',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='MkDir',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='MkNod',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='PathConf',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "NFSd v3 NFSd Requests by Method 2",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_nfsd_requests_total{method='Read',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='ReadDir',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='ReadDirPlus',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='ReadLink',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Remove',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Rename',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='RmDir',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='SetAttr',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='SymLink',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "rate(node_nfsd_requests_total{method='Write',proto='3',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  { "title": "NFSd v4 Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "NFSd v4 NFSd Requests by Method 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{method='Access',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Commit',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Create',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='GetAttr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Link',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Lookup',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Close',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='DelegPurge',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='DelegReturn',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='GetFH',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFSd v4 NFSd Requests by Method 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{method='Read',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='ReadDir',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='ReadLink',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Remove',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Rename',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='SetAttr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Write',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Lock',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Lockt',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Locku',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFSd v4 NFSd Requests by Method 3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total{method='LookupRoot',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Nverify',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Open',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='OpenAttr',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='OpenConfirm',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='OpenDgrd',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='PutFH',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='RelLockOwner',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Renew',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='RestoreFH',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='SaveFH',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='SecInfo',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "rate(node_nfsd_requests_total{method='Verify',proto='4',instance=~\"$node:$port\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}