{
 "title": "Nodesets Overview",
 "description": "For GB platforms",
 "tags": [
  "soperator",
  "nodesets",
  "overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "o11y", "label": "O11y" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_os_info, cluster)"
    }
   },
   {
    "name": "nodeset",
    "label": "Nodeset",
    "query": {
     "query": "label_values(slurm_node_info{cluster=~\"$cluster\"},nodeset_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Worker Node",
    "query": {
     "query": "label_values(slurm_node_info{cluster=~\"$cluster\", nodeset_name=~\"$nodeset\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "On GB platforms we create one Slurm Nodeset and one NVLink Instance Group per physical rack (18 nodes). <br>On other platforms Nodesets can have anywhere between 1 and 100 nodes."
   }
  },
  {
   "title": "NVLink Instance Groups",
   "type": "stat",
   "description": "For GB platform only",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(slurm_node_nvlink_instance_group{cluster=~\"$cluster\"}) by (cluster, nvlink_instance_group)\n) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "GPU Nodes",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  slurm_node_info{cluster=~\"$cluster\"}\n) by()"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\"}\n) by()"
    }
   ]
  },
  {
   "title": "GPU Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(\n    kube_node_labels{cluster=~\"$cluster\", label_nebius_com_gpu_name!=\"\", label_topology_nebius_com_nvl_instance_group_id!=\"\"}\n) by (label_nebius_com_gpu_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Mapping Nodeset to NVLIG to Instance ID",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "group (slurm_node_info{cluster=~\"$cluster\"}) by (node_name, nodeset_name, state_base, state_is_maintenance, state_is_not_responding, reason)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group (slurm_node_nvlink_instance_group{cluster=~\"$cluster\"}) by (node_name, nodeset_name, nvlink_instance_group, instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodesets Status",
   "type": "stat",
   "description": "\n",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH (\n    nodes = count by (nodeset_name, node_name) (\n        slurm_node_info{cluster=~\"$cluster\", \n            nodeset_name=~\"$nodeset\"\n        }\n    ),\n\n    healthy = count by (nodeset_name, node_name) (\n        slurm_node_info{cluster=~\"$cluster\", \n            state_base=~\"IDLE|ALLOCATED|MIXED\",\n            state_is_maintenance!=\"true\",\n            state_is_not_responding!=\"true\",\n            nodeset_name=~\"$nodeset\"\n        }\n    ),\n\n    total_nodes = count(nodes) by (nodeset_name),\n    healthy_nodes = count(healthy) by (nodeset_name)\n)\n\n# Healthy: every node is healthy\ngroup(\n    healthy_nodes == total_nodes\n) by (nodeset_name) * 1\nOR\n# Unhealthy: no healthy node exists\ngroup(\n    total_nodes unless on (nodeset_name) healthy_nodes\n) by (nodeset_name) * 2\nOR\n# Mixed: some, but not all, nodes are healthy\ngroup(\n    healthy_nodes < total_nodes\n) by (nodeset_name) * 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodesets Status Over Time",
   "type": "state-timeline",
   "description": "Timeline of NodeSet health. Healthy means all nodes are IDLE or ALLOCATED and neither in maintenance nor not responding; unhealthy means none are healthy; mixed means only some are healthy.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "WITH (\n    nodes = count by (nodeset_name, node_name) (\n        slurm_node_info{cluster=~\"$cluster\", \n            nodeset_name=~\"$nodeset\"\n        }\n    ),\n\n    healthy = count by (nodeset_name, node_name) (\n        slurm_node_info{cluster=~\"$cluster\", \n            state_base=~\"IDLE|ALLOCATED|MIXED\",\n            state_is_maintenance!=\"true\",\n            state_is_not_responding!=\"true\",\n            nodeset_name=~\"$nodeset\"\n        }\n    ),\n\n    total_nodes = count(nodes) by (nodeset_name),\n    healthy_nodes = count(healthy) by (nodeset_name)\n)\n\n# Healthy: every node is healthy\ngroup(\n    healthy_nodes == total_nodes\n) by (nodeset_name) * 1\nOR\n# Unhealthy: no healthy node exists\ngroup(\n    total_nodes unless on (nodeset_name) healthy_nodes\n) by (nodeset_name) * 2\nOR\n# Mixed: some, but not all, nodes are healthy\ngroup(\n    healthy_nodes < total_nodes\n) by (nodeset_name) * 3",
     "legendFormat": "{{nodeset_name}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Nodeset Utilization",
   "type": "timeseries",
   "description": "Proportion of GPUs with at least 10% utilization to total for selected nodesets",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", \n      slurm_nodeset_name=~\"$nodeset\"\n    }\n      >=\n    10\n  ) by(cluster)\n    /\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", \n      slurm_nodeset_name=~\"$nodeset\"\n    }\n  ) by(cluster)\n)\n  *\n100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodeset Power usage",
   "type": "timeseries",
   "description": "Only for GPUs with at least 10% utilization for selected nodesets",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", \n      slurm_nodeset_name=~\"$nodeset\"\n    }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", \n      slurm_nodeset_name=~\"$nodeset\"\n    }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", \n    slurm_nodeset_name=~\"$nodeset\"\n  }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", \n      slurm_nodeset_name=~\"$nodeset\"\n    }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)",
     "legendFormat": "avg"
    },
    {
     "expr": "min(\n  DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", \n    slurm_nodeset_name=~\"$nodeset\"\n  }\n    and on(exported_pod,gpu)\n  count(\n    DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", \n      slurm_nodeset_name=~\"$nodeset\"\n    }\n      >=\n    10\n  ) by(exported_pod,gpu)\n)",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Node Status for $nodeset",
   "type": "stat",
   "description": "\n",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "repeat": "nodeset",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Healthy\ncount by (nodeset_name, node_name) (\n    slurm_node_info{cluster=~\"$cluster\", \n        state_base=~\"IDLE|ALLOCATED|MIXED\",\n        state_is_maintenance!=\"true\",\n        state_is_not_responding!=\"true\",\n        node_name=~\"$node_name\",\n        nodeset_name=~\"$nodeset\"\n    }\n) * 1\nOR\n# Down\ncount by (nodeset_name, node_name) (\n    slurm_node_info{cluster=~\"$cluster\", \n        state_is_not_responding=\"true\",\n        state_is_maintenance!=\"true\",\n        node_name=~\"$node_name\",\n        nodeset_name=~\"$nodeset\"\n    }\n) * 2\nOR\n# Maintenance\ncount by (nodeset_name, node_name) (\n    slurm_node_info{cluster=~\"$cluster\", \n        state_is_maintenance=\"true\",\n        node_name=~\"$node_name\",\n        nodeset_name=~\"$nodeset\"\n    }\n) * 3",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}