{
 "title": "Workers Overview",
 "tags": [
  "nebius",
  "soperator",
  "workers-overview"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "o11y", "label": "O11y" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_os_info, cluster)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(kube_node_labels{cluster=~\"$cluster\", label_nebius_com_gpu_name=~\"GB.*\"},label_slurm_nebius_ai_nodeset_name)"
    }
   },
   {
    "name": "worker",
    "label": "Workers",
    "query": {
     "query": "label_values(slurm_node_info{cluster=~\"$cluster\", node_name=~\"$rack-.*\"}, node_name)"
    }
   },
   {
    "name": "hostname",
    "label": "instance",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\", pod=~\"$worker\"},node)"
    }
   },
   {
    "name": "ip",
    "label": "ip",
    "query": {
     "query": "label_values(node_uname_info{cluster=~\"$cluster\", container=\"node-exporter\", nodename=~\"$hostname\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage Guide",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "* You can select multiple workers from the Drop Down above\n* Stats in all panels will be based on selected workers\n"
   }
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Avg of utilization across all selected workers and instances",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (\n  1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\", mode=\"idle\"}[1m])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n    (\n        node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - \n        node_memory_MemFree_bytes{cluster=~\"$cluster\"} - \n        node_memory_Buffers_bytes{cluster=~\"$cluster\"} - \n        node_memory_Cached_bytes{cluster=~\"$cluster\"}\n    ) / \n    node_memory_MemTotal_bytes{cluster=~\"$cluster\", instance=~\"$ip\"}\n) * 100"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(node_filesystem_size_bytes{cluster=~\"$cluster\", device!=\"rootfs\",instance=~\"$ip\"}) - \n  sum(node_filesystem_avail_bytes{cluster=~\"$cluster\", device!=\"rootfs\",instance=~\"$ip\"})\n) / \nsum(node_filesystem_size_bytes{cluster=~\"$cluster\", device!=\"rootfs\",instance=~\"$ip\"})"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", exported_pod=~\"$worker\"})"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "stat",
   "description": "GPU Shutdown Temp: 90 C<br>\nGPU Slowdown Temp: 87 C<br>\nGPU Max Operating Temp: 83 C<br>",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", exported_pod=~\"$worker\"})"
    }
   ]
  },
  {
   "title": "GPU Avg. Mem. Cpy Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_SM_CLOCK{cluster=~\"$cluster\", exported_pod=~\"$worker\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Mem Clock",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{cluster=~\"$cluster\", exported_pod=~\"$worker\"}*1000000)"
    }
   ]
  },
  { "title": "Worker Placement ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Usage Guide",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": {
    "content": "* It shows the compute instance that a particular worker was scheduled on at any time\n* Worker that were moved to a different node will have more than one row for placement on each node\n* Workers that are added later (as scale up) would show with partial lines"
   }
  },
  {
   "title": "Slurm Node Placement History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sort_by_label(\n    group by (node, pod) (\n        kube_pod_info{cluster=~\"$cluster\", pod=~\"$worker\",node!=\"\"}\n    ),\n    \"pod\", \"node\"\n)",
     "legendFormat": "{{node}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Overall Stats (for selected workers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min(DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "GPU Mem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}/(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}+DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", exported_pod=~\"$worker\"}))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}/(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}+DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", exported_pod=~\"$worker\"}))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}/(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}+DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", exported_pod=~\"$worker\"}))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max (DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg (DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min (DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\", mode=\"idle\", instance=~\"$ip\"}[$__rate_interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\", mode=\"idle\", instance=~\"$ip\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\", mode=\"idle\", instance=~\"$ip\"}[$__rate_interval]))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "GPU Theoretical FLOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "tflops" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{cluster=~\"$cluster\", exported_pod=~\"$worker\"} * 1979)",
     "legendFormat": "FP8"
    },
    {
     "expr": "sum(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{cluster=~\"$cluster\", exported_pod=~\"$worker\"} * 989.7)",
     "legendFormat": "FP16/BF16"
    }
   ]
  },
  {
   "title": "Infiniband Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(node_infiniband_port_data_transmitted_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\"}[$__interval]))",
     "legendFormat": "Tx {{pod}}"
    },
    {
     "expr": "sum (rate(node_infiniband_port_data_received_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\"}[$__interval]))",
     "legendFormat": "Rx {{pod}}"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    (\n        node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - \n        node_memory_MemFree_bytes{cluster=~\"$cluster\"} - \n        node_memory_Buffers_bytes{cluster=~\"$cluster\"} - \n        node_memory_Cached_bytes{cluster=~\"$cluster\"}\n    )\n    /\n    node_memory_MemTotal_bytes{cluster=~\"$cluster\", instance=~\"$ip\"}\n)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(\n    (\n        node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - \n        node_memory_MemFree_bytes{cluster=~\"$cluster\"} - \n        node_memory_Buffers_bytes{cluster=~\"$cluster\"} - \n        node_memory_Cached_bytes{cluster=~\"$cluster\"}\n    )\n    /\n    node_memory_MemTotal_bytes{cluster=~\"$cluster\", instance=~\"$ip\"}\n)",
     "legendFormat": "avg"
    },
    {
     "expr": "min(\n    (\n        node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - \n        node_memory_MemFree_bytes{cluster=~\"$cluster\"} - \n        node_memory_Buffers_bytes{cluster=~\"$cluster\"} - \n        node_memory_Cached_bytes{cluster=~\"$cluster\"}\n    )\n    /\n    node_memory_MemTotal_bytes{cluster=~\"$cluster\", instance=~\"$ip\"}\n)",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "GPU Stats per Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GPU Avg Utilization per Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (exported_pod) (DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Mem Usage per Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (exported_pod) (DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}/(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", exported_pod=~\"$worker\"}+DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", exported_pod=~\"$worker\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Mem Copy Utilization per Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (exported_pod) (DCGM_FI_DEV_MEM_COPY_UTIL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Total Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (exported_pod) (DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Temperature per Worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (exported_pod) (DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XID errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum by (err_msg, exported_pod) (rate(DCGM_FI_DEV_XID_ERRORS{cluster=~\"$cluster\", exported_pod=~\"$worker\"}))",
     "legendFormat": "{{exported_pod}}: {{err_msg}}"
    }
   ]
  },
  {
   "title": "CPU, RAM, File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(1 - rate(node_cpu_seconds_total{cluster=~\"$cluster\", mode=\"idle\", instance=~\"$ip\"}[$__rate_interval])) by (instance)\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "System Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n    node_memory_MemTotal_bytes{cluster=~\"$cluster\"} - \n    node_memory_MemFree_bytes{cluster=~\"$cluster\"} - \n    node_memory_Buffers_bytes{cluster=~\"$cluster\"} - \n    node_memory_Cached_bytes{cluster=~\"$cluster\"}\n)\n/\nnode_memory_MemTotal_bytes{cluster=~\"$cluster\", instance=~\"$ip\"}\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\"}[$__interval]))\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "Read {{pod}}"
      },
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\"}[$__interval]))\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "Write {{pod}}"
      }
     ]
    },
    {
     "title": "Filesystem Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum by (instance, device) (node_filesystem_size_bytes{cluster=~\"$cluster\", instance=~\"$ip\"}) - \n  sum by (instance, device) (node_filesystem_avail_bytes{cluster=~\"$cluster\", instance=~\"$ip\"})\n) / \nsum by (instance, device) (node_filesystem_size_bytes{cluster=~\"$cluster\", instance=~\"$ip\",device!~\"none|shm|tmpfs|cloud-metadata|accounting|.*vda15\"})\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "{{device}} {{pod}}"
      }
     ]
    },
    {
     "title": "File Nodes Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance, device) (\n  1 - \n  (\n    node_filesystem_files_free{cluster=~\"$cluster\", instance=~\"$ip\",device!~'none|shm|tmpfs|cloud-metadata|accounting|.*vda15'}\n    /\n    node_filesystem_files{cluster=~\"$cluster\", instance=~\"$ip\",device!~'none|shm|tmpfs|cloud-metadata|accounting|.*vda15'}\n  )\n)\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "{{device}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\",device=~\"eth.*\"}[$__interval]))\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "Tx {{pod}}"
      },
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\",device=~\"eth.*\"}[$__interval]))\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "Rx {{pod}}"
      }
     ]
    },
    {
     "title": "Infiniband Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\"}[$__interval]))\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "Tx {{pod}}"
      },
      {
       "expr": "sum by (instance) (rate(node_infiniband_port_data_received_bytes_total{cluster=~\"$cluster\", instance=~\"$ip\"}[$__interval]))\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "Rx {{pod}}"
      }
     ]
    },
    {
     "title": "PCIe Throughput per Worker",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (exported_pod) (DCGM_FI_PROF_PCIE_TX_BYTES{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
       "legendFormat": "Tx {{exported_pod}}"
      },
      {
       "expr": "sum by (exported_pod) (DCGM_FI_PROF_PCIE_RX_BYTES{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
       "legendFormat": "Rx {{exported_pod}}"
      }
     ]
    },
    {
     "title": "NVLINK Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "1e6*sum by (exported_pod) (DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{cluster=~\"$cluster\", exported_pod=~\"$worker\"})",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    },
    {
     "title": "Infiniband Errors per Worker",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 180 },
     "targets": [
      {
       "expr": "sum by (instance) (\n  rate({cluster=~\"$cluster\", __name__=~\"node_infiniband_.*(error|downed|discards|dropped).*\", instance=~\"$ip\"}[$__interval])\n)\n* on(instance) group_left(nodename) node_uname_info{cluster=~\"$cluster\"}\n* on(nodename) group_left(pod) label_move(kube_pod_info{cluster=~\"$cluster\", pod=~\"worker.*\"}, \"node\", \"nodename\")",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Infiniband Errors per Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 180 },
     "targets": [
      {
       "expr": "sum by (error) (\n    rate(\n        label_copy(\n            {cluster=~\"$cluster\", __name__=~\"node_infiniband_.*(error|downed|discards|dropped).*\", instance=~\".*\"},\n            \"__name__\",\n            \"error\",\n        )[$__interval]\n    )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}