apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "run-check-on-reservation"
spec:
  checkType: "k8sJob"
  name: "run-check-on-reservation"
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  suspend: true
  runAfterCreation: true
  k8sJobSpec:
    jobContainer:
      command:
        - bash
        - -c
        - |
{{ .Files.Get "scripts/run-check-on-reservation.sh" | indent 10 }}
      image: {{ .Values.images.k8sJob | quote }}
      env:
        - name: RESERVATION_PREFEX
          value: {{ .Values.reservationPrefix | quote }}
        - name: TARGET_ACTIVE_CHECK_NAME
          value: {{ .Values.runCheckOnReservation.targetActiveCheckName | quote }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
