resources:
  - soperatorchecks.yaml
  - ../rbac/soperatorchecks/role.yaml
images:
  - name: controller
    newName: cr.eu-north1.nebius.cloud/soperator/soperatorchecks
    newTag: 4.1.2
patches:
  # Serve protected metrics from the manager using controller-runtime authn/authz.
  - path: ./manager_metrics_patch.yaml
