{{/* This file is generated by make sync-version. */}}

{{/* Container registry with stable Docker images */}}
{{- define "slurm-cluster.containerRegistry" -}}
    {{- "ghcr.io/nebius/soperator" -}}
{{- end }}
