{{- range $name, $volume := .Values.volumeSources }}
{{- if $volume.createPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ required "Claim name must be provided." $volume.persistentVolumeClaim.claimName | quote }}
  {{- with ($.Values.extraLabels | default dict) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with ($.Values.extraAnnotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ required "Volume size must be provided." $volume.size | quote }}
  storageClassName: {{ required "Storage class name must be provided." $volume.storageClassName | quote }}
{{- end }}
---
{{- end }}
