{{- if .Values.sConfigController.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-cluster.name" . }}-sconfigcontroller-metrics
  labels:
    app.kubernetes.io/name: sconfigcontroller-metrics
spec:
  type: ClusterIP
  ports:
  - name: https-metrics
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: sconfigcontroller
{{- end }}
