controllerManager:
  manager:
    args:
      - --health-probe-bind-address=:8081
      - --metrics-bind-address=:8443
      - --metrics-secure=true
      - --leader-elect
    controllersEnabled:
      cluster: true
      nodeconfigurator: true
      nodeset: true
      topology: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    env:
      isMariadbCrdInstalled: "false"
      isOpentelemetryCollectorCrdInstalled: "false"
      isApparmorCrdInstalled: "false"
      isPrometheusCrdInstalled: "false"
      slurmOperatorWatchNamespaces: '*'
      topologyLabelPrefix: "topology.nebius.com"
    image:
      repository: cr.eu-north1.nebius.cloud/soperator/slurm-operator
      tag: 4.1.4
    imagePullPolicy: Always
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  type: ClusterIP
serviceMonitor:
  enabled: true
  jobLabel: "soperator"
  interval: "30s"
  scrapeTimeout: "28s"
  additionalLabels: {}
  metricRelabelings: []
  relabelings: []
nodeExporter:
  enabled: false
  image:
    repository: cr.eu-north1.nebius.cloud/soperator-proxy-docker-io/prom/node-exporter
    tag: v1.10.2
    pullPolicy: IfNotPresent
  port: 9100
  args:
    - --collector.disable-defaults
    - --collector.netdev
    - --collector.netstat
    - --collector.sockstat
    - --collector.conntrack
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 64Mi
  podMonitor:
    interval: "30s"
    scrapeTimeout: "10s"
    metricRelabelings: []
    relabelings: []
certManager:
  enabled: true
kruise:
  installOperator: false
  manager:
    replicas: 1
  featureGates: "ImagePullJobGate=true,RecreatePodWhenChangeVCTInCloneSetGate=true,StatefulSetAutoResizePVCGate=true,StatefulSetAutoDeletePVC=true,PreDownloadImageForInPlaceUpdate=true,ResourceDistributionGate=true"
