package sharedsteps

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/nebius/soperator/e2e/acceptance/framework"
)

// renderedTopologyConfig is the topology.yaml the operator publishes, warning header included.
const renderedTopologyConfig = `# Managed by Soperator.
# Do not edit this file.
# Changes are overwritten.

- topology: flat
  cluster_default: true
  flat: true
- topology: tree-ib
  cluster_default: false
  tree:
    switches:
        - switch: leaf-a
          nodes: worker-1
        - switch: spine-a
          children: leaf-a,leaf-b
        - switch: leaf-b
          nodes: worker-block-0
        - switch: fabric
          children: spine-a,fabric.unknown
        - switch: fabric.unknown
          nodes: worker-2
- topology: block-nvl72
  cluster_default: false
  block:
    block_sizes:
        - 2
    blocks:
        - block: block-0
          nodes: worker-block-[0-1]
`

// loadedTopologyConfig is the same file as "scontrol show topoconf" prints it back: YAML document
// markers, and the plugins an entry does not use spelled as empty maps.
const loadedTopologyConfig = `%YAML 1.1
---
- topology: flat
  cluster_default: true
  block: {}
  flat: true
  ring: {}
  torus3d: {}
  tree: {}
- topology: tree-ib
  cluster_default: false
  block: {}
  flat: {}
  ring: {}
  torus3d: {}
  tree:
    switches:
    - switch: leaf-a
      children:
      nodes: worker-1
    - switch: spine-a
      children: leaf-a,leaf-b
      nodes:
    - switch: leaf-b
      children:
      nodes: worker-block-0
    - switch: fabric
      children: spine-a,fabric.unknown
      nodes:
    - switch: fabric.unknown
      children:
      nodes: worker-2
- topology: block-nvl72
  cluster_default: false
  block:
    block_sizes:
    - 2
    blocks:
    - block: block-0
      nodes: worker-block-[0-1]
  flat: {}
  ring: {}
  torus3d: {}
  tree: {}
...
`

const showTopologyTree = `SwitchName=leaf-a Level=0 LinkSpeed=0 Nodes=worker-1
SwitchName=spine-a Level=1 LinkSpeed=0 Nodes=worker-1,worker-block-0 Switches=leaf-a,leaf-b
SwitchName=leaf-b Level=0 LinkSpeed=0 Nodes=worker-block-0
SwitchName=fabric Level=2 LinkSpeed=0 Nodes=worker-[0-2],worker-block-[0-1] Switches=spine-a,fabric.unknown
SwitchName=fabric.unknown Level=0 LinkSpeed=0 Nodes=worker-2
`

const showTopologyBlock = `BlockName=block-0 BlockIndex=0 Nodes=worker-block-[0-1] BlockSize=2
`

const showNodes = `NodeName=worker-0 Arch=x86_64 CoresPerSocket=40
   State=IDLE+CLOUD ThreadsPerCore=2 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Topology=tree-ib:fabric:spine-a:leaf-a

NodeName=worker-2 CoresPerSocket=40
   State=IDLE+CLOUD+POWERED_DOWN ThreadsPerCore=2 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A

NodeName=worker-block-0 Arch=x86_64 CoresPerSocket=40
   State=IDLE+CLOUD ThreadsPerCore=2 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Topology=tree-ib:fabric:spine-a:leaf-b,block-nvl72:block-0

NodeName=worker-ephemral-0 Arch=x86_64 CoresPerSocket=8
   State=IDLE+CLOUD ThreadsPerCore=2 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
`

const showPartitions = `PartitionName=worker
   AllocNodes=ALL Default=NO QoS=N/A
   Nodes=worker-[0-2]
   Topology=tree-ib
   State=UP TotalCPUs=480 TotalNodes=3 SelectTypeParameters=NONE

PartitionName=main
   AllocNodes=ALL Default=YES QoS=N/A
   Nodes=worker-[0-2],worker-block-[0-1],worker-ephemral-[0-15]
   Topology=flat
   State=UP TotalCPUs=1056 TotalNodes=21 SelectTypeParameters=NONE
`

func TestParseTopologyEntriesReadsTheRenderedConfig(t *testing.T) {
	entries, err := parseTopologyEntries(renderedTopologyConfig)
	require.NoError(t, err)
	require.Len(t, entries, 3)

	assert.Equal(t, "flat", entries[0].Name)
	assert.Equal(t, topologyKindFlat, entries[0].Kind)
	assert.True(t, entries[0].ClusterDefault)

	assert.Equal(t, topologyKindTree, entries[1].Kind)
	assert.False(t, entries[1].ClusterDefault)
	require.Len(t, entries[1].Switches, 5)
	assert.Equal(t, "leaf-a", entries[1].Switches[0].Name)
	assert.Equal(t, "worker-1", entries[1].Switches[0].Nodes)
	assert.Equal(t, []string{"leaf-a", "leaf-b"}, entries[1].Switches[1].Children)

	assert.Equal(t, topologyKindBlock, entries[2].Kind)
	assert.Equal(t, []int{2}, entries[2].BlockSizes)
	require.Len(t, entries[2].Blocks, 1)
	assert.Equal(t, "worker-block-[0-1]", entries[2].Blocks[0].Nodes)
}

// The two spellings of one file must reduce to the same structure, or comparing what slurmctld
// loaded against what the operator published would report a difference that is only formatting.
func TestParseTopologyEntriesReadsTopoconfTheSameWay(t *testing.T) {
	rendered, err := parseTopologyEntries(renderedTopologyConfig)
	require.NoError(t, err)
	loaded, err := parseTopologyEntries(loadedTopologyConfig)
	require.NoError(t, err)

	assert.Equal(t,
		"flat=flat:[]:true,tree-ib=tree:[]:false,block-nvl72=block:[2]:false",
		topologyStructure(rendered))
	assert.Equal(t, topologyStructure(rendered), topologyStructure(loaded))
}

func TestParseTopologyEntriesRejectsMalformedConfigs(t *testing.T) {
	for name, raw := range map[string]string{
		"empty":         "",
		"no name":       "- cluster_default: true\n  flat: true\n",
		"no plugin":     "- topology: nowhere\n  cluster_default: true\n",
		"two plugins":   "- topology: both\n  flat: true\n  tree:\n    switches:\n      - switch: s\n",
		"duplicate":     "- topology: twice\n  flat: true\n- topology: twice\n  flat: true\n",
		"empty plugins": "- topology: none\n  tree: {}\n  block: {}\n  flat: {}\n",
	} {
		t.Run(name, func(t *testing.T) {
			_, err := parseTopologyEntries(raw)
			assert.Error(t, err)
		})
	}
}

func TestParseSlurmSwitchesFindsTheLeaves(t *testing.T) {
	switches, err := parseSlurmSwitches(showTopologyTree)
	require.NoError(t, err)
	require.Len(t, switches, 5)

	leaves := make(map[string]string)
	for _, sw := range switches {
		if sw.IsLeaf() {
			leaves[sw.Name] = sw.Nodes
		}
	}
	assert.Equal(t, map[string]string{
		"leaf-a":         "worker-1",
		"leaf-b":         "worker-block-0",
		"fabric.unknown": "worker-2",
	}, leaves)

	assert.Equal(t, 1, switches[1].Level)
	assert.Equal(t, []string{"leaf-a", "leaf-b"}, switches[1].Children)
	// An ancestor lists every descendant node, which is why only Level=0 identifies a node's switch.
	assert.Equal(t, "worker-1,worker-block-0", switches[1].Nodes)
}

func TestParseSlurmSwitchesRejectsOutputWithoutSwitches(t *testing.T) {
	_, err := parseSlurmSwitches("slurm_load_topo error: Requested topology configuration is not available")
	assert.Error(t, err)
}

func TestParseSlurmBlocks(t *testing.T) {
	blocks, err := parseSlurmBlocks(showTopologyBlock)
	require.NoError(t, err)
	require.Len(t, blocks, 1)
	assert.Equal(t, slurmBlock{Name: "block-0", Nodes: "worker-block-[0-1]", Size: 2}, blocks[0])
}

func TestParseNodeTopologies(t *testing.T) {
	blocks := parseScontrolBlocks(showNodes, "NodeName")
	require.Len(t, blocks, 4)

	assert.Equal(t,
		map[string]string{"tree-ib": "fabric:spine-a:leaf-a"},
		parseNodeTopologies(blocks["worker-0"]))
	assert.Equal(t,
		map[string]string{"tree-ib": "fabric:spine-a:leaf-b", "block-nvl72": "block-0"},
		parseNodeTopologies(blocks["worker-block-0"]))

	// A powered-down worker and a CPU-only one both register into nothing.
	assert.Nil(t, parseNodeTopologies(blocks["worker-2"]))
	assert.Nil(t, parseNodeTopologies(blocks["worker-ephemral-0"]))
}

func TestRegisteredLeafTakesTheLastPathSegment(t *testing.T) {
	assert.Equal(t, "leaf-a", registeredLeaf("fabric:spine-a:leaf-a"))
	assert.Equal(t, "block-0", registeredLeaf("block-0"))
	assert.Equal(t, "", registeredLeaf(""))
}

func TestParsePartitions(t *testing.T) {
	partitions := parsePartitions(showPartitions)
	assert.Equal(t, []partitionInfo{
		{Name: "main", Topology: "flat", Nodes: "worker-[0-2],worker-block-[0-1],worker-ephemral-[0-15]"},
		{Name: "worker", Topology: "tree-ib", Nodes: "worker-[0-2]"},
	}, partitions)
}

func TestSrunRefusedOnlyMatchesPlacementFailures(t *testing.T) {
	refusal := errors.New(`srun: error: Unable to allocate resources: Requested nodes are busy`)
	assert.True(t, srunRefused("srun: job 108 queued and waiting for resources", refusal))
	assert.True(t, srunRefused("", errors.New("Requested node configuration is not available")))

	assert.False(t, srunRefused("worker-0", nil))
	assert.False(t, srunRefused("", errors.New("error: connection refused")))
}

func TestHalveBlockSizes(t *testing.T) {
	// Only the base is halved: the aggregation levels above it stay as the cluster declares them.
	sizes, ok := halveBlockSizes([]int{4, 16})
	assert.True(t, ok)
	assert.Equal(t, []int{2, 16}, sizes)

	sizes, ok = halveBlockSizes([]int{8})
	assert.True(t, ok)
	assert.Equal(t, []int{4}, sizes)

	// A base size of one cannot be halved into a valid configuration.
	_, ok = halveBlockSizes([]int{1})
	assert.False(t, ok)
	_, ok = halveBlockSizes(nil)
	assert.False(t, ok)
}

func TestPlainHostlistDefersRangesToScontrol(t *testing.T) {
	nodes, ok := plainHostlist("worker-0,worker-1")
	assert.True(t, ok)
	assert.Equal(t, []string{"worker-0", "worker-1"}, nodes)

	nodes, ok = plainHostlist("(null)")
	assert.True(t, ok)
	assert.Nil(t, nodes)

	_, ok = plainHostlist("worker-[0-2]")
	assert.False(t, ok)
}

func TestSrunRequestCommand(t *testing.T) {
	unconstrained := srunRequest{
		Partition: "worker",
		Nodes:     []string{"worker-0", "worker-1"},
		Immediate: topologyJobImmediate,
	}
	assert.Equal(t,
		"timeout 150 srun --immediate=90 -p 'worker' -N 2 -n 2 --ntasks-per-node=1 -w 'worker-0,worker-1' --time=1:00 hostname",
		unconstrained.command())

	constrained := unconstrained
	constrained.Switches = 1
	constrained.Immediate = topologyDenyImmediate
	assert.Equal(t,
		"timeout 90 srun --immediate=30 -p 'worker' -N 2 -n 2 --ntasks-per-node=1 -w 'worker-0,worker-1' --time=1:00 --switches=1 hostname",
		constrained.command())
}

// A tree of "root + one leaf" is valid configuration and holds every worker within one switch, so
// it cannot demonstrate a switch constraint. Counting switches rather than leaves would let it
// through the gate and fail later, on state, instead of skipping here.
func TestLeafSwitchesCountsOnlyTheSwitchesCarryingWorkers(t *testing.T) {
	branching, err := parseTopologyEntries(renderedTopologyConfig)
	require.NoError(t, err)
	require.Len(t, branching, 3)
	assert.Equal(t, 3, leafSwitches(branching[1]))

	singleLeaf, err := parseTopologyEntries(`
- topology: tree-ib
  cluster_default: true
  tree:
    switches:
        - switch: root
          children: leaf-a
        - switch: leaf-a
          nodes: worker-[0-1]
`)
	require.NoError(t, err)
	require.Len(t, singleLeaf, 1)
	assert.Equal(t, 1, leafSwitches(singleLeaf[0]))
}

func TestPickLeafPairs(t *testing.T) {
	leaves := []string{"leaf-a", "leaf-b", "leaf-c"}
	nodesByLeaf := map[string][]string{
		"leaf-a": {"worker-0", "worker-1"},
		"leaf-b": {"worker-2"},
		"leaf-c": {"worker-3"},
	}
	all := func(string) bool { return true }

	t.Run("picks one pair across leaves and one within a leaf", func(t *testing.T) {
		cross, same := pickLeafPairs(leaves, nodesByLeaf, "tree-ib", "worker", all)
		require.NotNil(t, cross)
		assert.Equal(t, [2]string{"worker-0", "worker-2"}, cross.Nodes)
		assert.Equal(t, [2]string{"leaf-a", "leaf-b"}, cross.Leaves)
		require.NotNil(t, same)
		assert.Equal(t, [2]string{"worker-0", "worker-1"}, same.Nodes)
	})

	// The busy cluster the scenario skips on: the tree still separates its workers, none of them
	// can take a job.
	t.Run("reports no pair when the workers it would use are busy", func(t *testing.T) {
		idle := func(node string) bool { return node == "worker-0" || node == "worker-1" }
		cross, same := pickLeafPairs(leaves, nodesByLeaf, "tree-ib", "worker", idle)
		assert.Nil(t, cross)
		require.NotNil(t, same)
		assert.Equal(t, [2]string{"worker-0", "worker-1"}, same.Nodes)
	})

	t.Run("skips a leaf whose workers are all filtered out", func(t *testing.T) {
		idle := func(node string) bool { return node != "worker-2" }
		cross, _ := pickLeafPairs(leaves, nodesByLeaf, "tree-ib", "worker", idle)
		require.NotNil(t, cross)
		assert.Equal(t, [2]string{"worker-0", "worker-3"}, cross.Nodes)
		assert.Equal(t, [2]string{"leaf-a", "leaf-c"}, cross.Leaves)
	})
}

// Ready and Idle answer different questions: a worker running someone else's job is healthy and
// registered, and asking for it would make the scenario wait that job out.
func TestSlurmNodeViewReadyAndIdle(t *testing.T) {
	for _, tc := range []struct {
		state string
		ready bool
		idle  bool
	}{
		{state: "IDLE+CLOUD", ready: true, idle: true},
		{state: "ALLOCATED+CLOUD", ready: true, idle: false},
		{state: "MIXED+CLOUD", ready: true, idle: false},
		{state: "IDLE+CLOUD+POWERED_DOWN", ready: false, idle: false},
		{state: "IDLE+DRAIN", ready: false, idle: false},
		{state: "DOWN+CLOUD", ready: false, idle: false},
	} {
		t.Run(tc.state, func(t *testing.T) {
			view := slurmNodeView{Info: framework.SlurmNodeInfo{Name: "worker-0", State: tc.state}}
			assert.Equal(t, tc.ready, view.Ready())
			assert.Equal(t, tc.idle, view.Idle())
		})
	}
}
