include /etc/nginx/modules-enabled/*.conf;

user root;
worker_processes auto;
pid /var/run/nginx-soperator-docker-proxy.pid;

error_log /dev/stderr info;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    client_max_body_size 0;
    js_import docker_proxy from /etc/nginx/njs/docker_proxy.js;
    js_var $docker_request_uri;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream docker_daemon {
        server unix:/var/run/docker.sock;
        keepalive 32;
    }

    server {
        listen unix:/var/run/soperator-docker.sock;

        location = /containers/create {
            js_content docker_proxy.handleCreate;
        }

        location ~ ^/v\d+(?:\.\d+)?/containers/create$ {
            js_content docker_proxy.handleCreate;
        }

        location /_docker_upstream {
            internal;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_read_timeout 1d;
            proxy_send_timeout 1d;
            proxy_set_header Host docker;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://docker_daemon$docker_request_uri;
        }

        location / {
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_read_timeout 1d;
            proxy_send_timeout 1d;
            proxy_set_header Host docker;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://docker_daemon;
        }
    }
}
