---

- name: Install/Upgrade nc-health-checker
  hosts:
    - all
    - localhost
  become: true
  gather_facts: true
  gather_subset:
    - min
  roles:
    - nc_health_checker
  tags:
    - nc_health_checker
