# syntax=docker.io/docker/dockerfile-upstream:1.20.0

ARG SLURM_VERSION

FROM cr.eu-north1.nebius.cloud/soperator-proxy-docker-io/library/golang:1.26 AS login_docker_proxy_builder

WORKDIR /src
COPY go.mod go.sum ./
COPY cmd/login-docker-proxy ./cmd/login-docker-proxy
RUN CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags='-s -w' \
    -o /out/login-docker-proxy \
    ./cmd/login-docker-proxy

# https://github.com/nebius/ml-containers/pull/99
FROM cr.eu-north1.nebius.cloud/ml-containers/slurm:${SLURM_VERSION}-20260816173636 AS login_pam_builder

RUN apt-get update && \
    apt-get install -y libpam0g-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY images/login/pam_soperator_jail.c /usr/src/pam-soperator-jail/
RUN PAM_MODULE_DIR="/out/usr/lib/$(gcc -print-multiarch)/security" && \
    mkdir -p "${PAM_MODULE_DIR}" && \
    gcc \
        -std=c11 \
        -Wall \
        -Wextra \
        -Werror \
        -fPIC \
        -shared \
        -Wl,-z,defs \
        -Wl,-z,now \
        -Wl,-z,relro \
        -o "${PAM_MODULE_DIR}/pam_soperator_jail.so" \
        /usr/src/pam-soperator-jail/pam_soperator_jail.c \
        -lpam && \
    chmod 0644 "${PAM_MODULE_DIR}/pam_soperator_jail.so"

# https://github.com/nebius/ml-containers/pull/99
FROM cr.eu-north1.nebius.cloud/ml-containers/slurm:${SLURM_VERSION}-20260816173636 AS login_sshd

# Install OpenSSH server and process-supervision dependencies
# Create root .ssh directory
# Remove autogenerated sshd server keys
RUN apt-get update && \
    apt install -y \
        openssh-server \
        supervisor && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -m 700 -p /root/.ssh && \
    rm -rf /etc/ssh/ssh_host*key*

COPY ansible/docker.yml /opt/ansible/docker.yml
COPY ansible/roles/docker /opt/ansible/roles/docker
RUN cd /opt/ansible && \
    ansible-playbook -i inventory/ -c local docker.yml -t docker && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create dummy library for replacing GPU-specific libraries with it
RUN ALT_ARCH="$(uname -m)" && \
    mkdir -p /usr/src/dummy && \
    cd /usr/src/dummy && \
    echo 'int main() { return 0; }' > dummy.c && \
    gcc -shared -o libdummy.so dummy.c && \
    mkdir -p "/lib/${ALT_ARCH}-linux-gnu" && \
    cp libdummy.so "/lib/${ALT_ARCH}-linux-gnu/"

COPY ansible/sssd.yml /opt/ansible/sssd.yml
COPY ansible/roles/sssd /opt/ansible/roles/sssd
RUN cd /opt/ansible && \
    ansible-playbook -i inventory/ -c local sssd.yml

# Install slurm сhroot plugin
COPY images/common/chroot-plugin/chroot.c /usr/src/chroot-plugin/
COPY images/common/scripts/install_chroot_plugin.sh /opt/bin/
RUN chmod +x /opt/bin/install_chroot_plugin.sh && \
    /opt/bin/install_chroot_plugin.sh && \
    rm /opt/bin/install_chroot_plugin.sh

# Install NCCL Debug SPANK plugin
COPY images/common/spank-nccl-debug/src /usr/src/soperator/spank/nccld-debug
COPY images/common/scripts/install_nccld_debug_plugin.sh /opt/bin/
RUN chmod +x /opt/bin/install_nccld_debug_plugin.sh && \
    /opt/bin/install_nccld_debug_plugin.sh && \
    rm /opt/bin/install_nccld_debug_plugin.sh

# Install NCCL Inspector PreConf SPANK plugin
COPY ansible/spank-nccl-inspector-preconf.yml /opt/ansible/spank-nccl-inspector-preconf.yml
COPY ansible/roles/spank-nccl-inspector-preconf /opt/ansible/roles/spank-nccl-inspector-preconf
RUN cd /opt/ansible && \
    ansible-playbook -i inventory/ -c local \
      -e spank_nccl_inspector_preconf_dump_dir_create=false \
      spank-nccl-inspector-preconf.yml

# Install enroot
COPY images/common/scripts/install_enroot.sh /opt/bin/
RUN chmod +x /opt/bin/install_enroot.sh && \
    /opt/bin/install_enroot.sh && \
    rm /opt/bin/install_enroot.sh

# Copy enroot configuration
COPY images/common/enroot/enroot.conf /etc/enroot/
COPY images/common/enroot/custom-dirs.conf /etc/enroot/enroot.conf.d/
RUN chown 0:0 /etc/enroot/enroot.conf && \
    chmod 644 /etc/enroot/enroot.conf && \
    chown 0:0 /etc/enroot/enroot.conf.d/custom-dirs.conf && \
    chmod 644 /etc/enroot/enroot.conf.d/custom-dirs.conf

ARG SLURM_DEB_VERSION
ARG PYXIS_VERSION=0.24.0
# Install slurm pyxis plugin
RUN apt-get update && \
    apt -y install nvslurm-plugin-pyxis=${SLURM_DEB_VERSION}-${PYXIS_VERSION}-1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy script for complementing jail filesystem in runtime
COPY images/common/scripts/complement_jail.sh /opt/bin/slurm/

# Copy script for bind-mounting slurm into the jail
COPY images/common/scripts/bind_slurm_common.sh /opt/bin/slurm/

RUN chmod +x /opt/bin/slurm/complement_jail.sh && \
    chmod +x /opt/bin/slurm/bind_slurm_common.sh

# Update linker cache
RUN ldconfig

# Delete users & home because they will be linked from jail
RUN rm /etc/passwd* /etc/group* /etc/shadow* /etc/gshadow*
RUN rm -rf /home

# Delete SSH "message of the day" scripts because they will be linked from jail
RUN rm -rf /etc/update-motd.d

# Install the native PAM module that places each SSH session in its own mount
# namespace and pivots it into /mnt/jail.
COPY --from=login_pam_builder /out/ /

# Install the per-user cgroup isolation PAM hook.
# It is a no-op unless enabled via the SlurmCluster `login.userIsolation` field.
COPY images/login/user_isolation_pam_hook.sh /opt/bin/slurm/
RUN chmod +x /opt/bin/slurm/user_isolation_pam_hook.sh && \
    echo "session optional pam_exec.so quiet log=/proc/1/fd/1 /opt/bin/slurm/user_isolation_pam_hook.sh" >> /etc/pam.d/sshd && \
    echo "session required pam_soperator_jail.so /mnt/jail" >> /etc/pam.d/sshd

# Install login Docker daemon and proxy configuration. Docker remains inactive
# unless enabled in the SlurmCluster login configuration.
COPY images/login/docker/daemon.json /etc/docker/daemon.json
COPY images/login/supervisord.conf /etc/supervisor/conf.d/soperator-login.conf
COPY --from=login_docker_proxy_builder /out/login-docker-proxy /opt/bin/slurm/login-docker-proxy
COPY images/login/dockerd_entrypoint.sh /opt/bin/slurm/
COPY images/login/sshd_supervised_entrypoint.sh /opt/bin/slurm/
RUN chmod +x \
        /opt/bin/slurm/login-docker-proxy \
        /opt/bin/slurm/dockerd_entrypoint.sh \
        /opt/bin/slurm/sshd_supervised_entrypoint.sh

# Expose the port used for accessing sshd
EXPOSE 22

# Copy & run the entrypoint script
COPY images/login/sshd_entrypoint.sh /opt/bin/slurm/
RUN chmod +x /opt/bin/slurm/sshd_entrypoint.sh
ENTRYPOINT ["/opt/bin/slurm/sshd_entrypoint.sh"]
