[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:sshd]
priority=10
command=/opt/bin/slurm/sshd_supervised_entrypoint.sh
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10

[program:dockerd]
priority=20
command=/opt/bin/slurm/dockerd_entrypoint.sh
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10
