[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:dockerd]
priority=10
command=/opt/bin/slurm/dockerd_entrypoint.sh
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=30

[program:docker-proxy]
priority=20
command=/opt/bin/slurm/docker_proxy_entrypoint.sh login --listen=/var/run/docker.sock --upstream=/run/soperator-dockerd.sock
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10

[program:sshd]
priority=30
command=/usr/sbin/sshd -D -e -f /mnt/ssh-configs/sshd_config
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10
