load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "naming",
    srcs = ["naming.go"],
    importpath = "nebius.ai/slurm-operator/internal/models/k8s/naming",
    visibility = ["//msp/slurm-service:__subpackages__"],
    deps = ["//msp/slurm-service/internal/operator/internal/consts"],
)
