name: "Auto merge back"

on:
  push:
    branches:
      - 'soperator-release-*'

jobs:
  create-merge-back-pr:
    name: Create merge back PR
    runs-on: self-hosted

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Run auto merge-back workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/workflows/scripts/auto-merge-back.sh
