load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "renderutils",
    srcs = ["config.go"],
    importpath = "nebius.ai/slurm-operator/internal/render/utils",
    visibility = ["//msp/slurm-service:__subpackages__"],
)
